### ISSUE TITLE
Error 500 when calling a repo

### ISSUE THREAD

**Issue by ymolinet** [jbox-web/redmine_git_hosting#180]
One of our GIT REPO, and only one, crash with error 500 when we open the repo in redmine. GIT command working correctly using Tortoise as client.

```
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"dixinfor-plugin-glpi-r-i"}
  Current user: Yannick (id=3)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_git_urls.html.erb (9.0ms)
  Rendered repositories/_navigation.html.erb (15.6ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/show.html.erb within layouts/base (25.8ms)
Completed 500 Internal Server Error in 280.5ms

ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8):
    27:                    :id => 'tag' %>
    28:   <% end -%>
    29:
    30:   <% if @repository.supports_all_revisions? %>
    31:     | <%= l(:label_revision) %>:
    32:     <%= text_field_tag 'rev', @rev, :size => 8 %>
    33:   <% end %>
  app/views/repositories/_navigation.html.erb:30:in `block in _app_views_repositories__navigation_html_erb___644956614940436259_49904540'
  app/views/repositories/_navigation.html.erb:13:in `_app_views_repositories__navigation_html_erb___644956614940436259_49904540'
  app/controllers/repositories_controller.rb:125:in `show'
```

**Comment by Idleworks** [comment]
I ran into the same issue today after pushed last commit. Got mysql2 adapter running and have already checked utf-8 settings in configuration files.

Here is my error thrown by redmine:
```
Started GET "/projects/na15-extensions/repository" for XXX at 2015-10-30 12:53:10 +0000
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"na15-extensions"}
  Current user: idler (id=3)
  Rendered repositories/_navigation.html.erb (21.1ms)
  Rendered repositories/_breadcrumbs.html.erb (0.6ms)
  Rendered repositories/_dir_list_content.html.erb (28.1ms)
  Rendered repositories/_dir_list.html.erb (28.5ms)
  Rendered repositories/_revision_graph.html.erb (2.1ms)
  Rendered repositories/_revisions.html.erb (32.8ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/show.html.erb within layouts/base (762.3ms)
Completed 500 Internal Server Error in 852ms

ActionView::Template::Error ("\xC3" from ASCII-8BIT to UTF-8):
    47:                        :id => @project, :page => nil, :key => User.current.rss_key})) %>
    48:    <% end %>
    49: 
    50:    <%= call_hook(:view_repositories_show_bottom) %>
    51: 
    52:    <% other_formats_links do |f| %>
    53:     <%= f.link_to 'Atom',
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
```

**Comment by Idleworks** [comment]
Tracked it down a bit, I'll create a new issue
