### ISSUE TITLE
Rake failing during migration to v0.8-beta

### ISSUE THREAD

**Issue by DProvorse** [jbox-web/redmine_git_hosting#325]
```
old_name : 2011072600000-redmine_git_hosting
new_name : 20110726000000-redmine_git_hosting
Already migrated, pass!

old_name : 2011080700000-redmine_git_hosting
new_name : 20110807000000-redmine_git_hosting
Already migrated, pass!

old_name : 2011081300000-redmine_git_hosting
new_name : 20110813000000-redmine_git_hosting
Already migrated, pass!

old_name : 2011081700000-redmine_git_hosting
new_name : 20110817000000-redmine_git_hosting
Already migrated, pass!

old_name : 2012052100000-redmine_git_hosting
new_name : 20120521000000-redmine_git_hosting
Already migrated, pass!

old_name : 2012052100001-redmine_git_hosting
new_name : 20120521000010-redmine_git_hosting
Already migrated, pass!

old_name : 2012052200000-redmine_git_hosting
new_name : 20120522000000-redmine_git_hosting
Already migrated, pass!

Done!
Migrating redmine_git_hosting (Redmine Git Hosting Plugin)...
==  RemoveNotifyCia: migrating ================================================
-- drop_table(:git_cia_notifications)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Unknown table 'git_cia_notifications': DROP TABLE `git_cia_notifications`/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/connection_adapters/mysql2_adapter.rb:213:in `execute'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/schema_statements.rb:256:in `drop_table'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:466:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:438:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:438:in `say_with_time'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:458:in `method_missing'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:334:in `method_missing'
/home/redmine/redmine/plugins/redmine_git_hosting/db/migrate/20140305053200_remove_notify_cia.rb:4:in `up'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:370:in `up'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:410:in `block in migrate'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:389:in `migrate'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:528:in `migrate'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:777:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:777:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:719:in `block in migrate'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:700:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:700:in `migrate'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:570:in `up'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activerecord-3.2.19/lib/active_record/migration.rb:551:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:469:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:441:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:452:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/plugins/redmine_git_hosting/lib/tasks/migration_tools.rake:85:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p594/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p594/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by DProvorse** [comment]
Ended up completely blowing everything out of the DB and plugins directory and building back from scratch which solved the problem.

**Comment by n-rodriguez** [comment]
A bit radical ^^

**Comment by n-rodriguez** [comment]
But I should have warned you... The v0.8 version has been dropped out.

**Comment by DProvorse** [comment]
Ahhh so is the devel branch the better one to run on for testing?

**Comment by n-rodriguez** [comment]
For testing yes, the devel branch but if you want to switch to **real production** utilization later, the v1.0.0-beta is more appropriate.

Currently the devel branch and the v1.0.0 branch are identical but the devel branch may evolve in a near futur which may impact the database schema.

**Comment by n-rodriguez** [comment]
Also : you should read this before https://jbox-web.github.io/redmine_git_hosting/news/index.html

**Comment by n-rodriguez** [comment]
The changelog of the for the V1 : https://jbox-web.github.io/redmine_git_hosting/about/releases-notes/#toc-release-1-0-0

**Comment by n-rodriguez** [comment]
Note that the documentation is not finished yet but basically : 
* if you start from scratch you have nothing special to do (except the [*classic install*](https://jbox-web.github.io/redmine_git_hosting/howtos/index.html#step-by-step-installation))
* if you come from v0.7 you must upgrade to v0.7.9 first
then run ````RAILS_ENV=production bundle exec rake redmine_git_hosting:migration_tools:prepare_migration_to_v1```

**Comment by DProvorse** [comment]
I'll move to 1.0.0-beta for this box. So from setting at v0.7.9 if I run the above rake I get the following.

Don't know how to build task 'redmine_git_hosting:migration_tools:prepare_migration_to_v1'

**Comment by n-rodriguez** [comment]
Sorry it's ```redmine_git_hosting:prepare_migration_to_v1```

**Comment by DProvorse** [comment]
So after doing the initial migration to v1 with the updated command and then doing a checkout to v1.0.0-beta when I attempt to run the second migration it fails with the following.

ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '20110807000000-redmine_git_hosting' for key 'unique_schema_migrations': INSERT INTO schema_migrations (VERSION) VALUES ('20110807000000-redmine_git_hosting');

**Comment by n-rodriguez** [comment]
Weird... that means there is a bug around here : https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/tasks/migration_tools.rake#L21
