### ISSUE TITLE
Crash since 1.0.0 migration

### ISSUE THREAD

**Issue by llaumgui** [jbox-web/redmine_git_hosting#332]
Hi,
i have tried to migrate from 0.7.10 to 1.0.0. I have 1 issue in migration:

~~~
Migrating redmine_git_hosting (Redmine Git Hosting Plugin)...

Delete SSH keys in Gitolite and reset identifier :

  - Delete SSH key redmine_azerty@redmine_1403614163_646200
rake aborted!
Rugged::NetworkError: This transport isn't implemented. Sorry
/opt/redmine/redmine261/vendor/bundle/ruby/1.9.1/bundler/gems/gitolite-rugged-0f6378ca10c7/lib/gitolite/gitolite_admin.rb:297:in `clone_at'
/opt/redmine/redmine261/vendor/bundle/ruby/1.9.1/bundler/gems/gitolite-rugged-0f6378ca10c7/lib/gitolite/gitolite_admin.rb:297:in `clone'
/opt/redmine/redmine261/vendor/bundle/ruby/1.9.1/bundler/gems/gitolite-rugged-0f6378ca10c7/lib/gitolite/gitolite_admin.rb:104:in `initialize'
/opt/redmine/redmine261/plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:67:in `new'
/opt/redmine/redmine261/plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:67:in `gitolite_admin'
/opt/redmine/redmine261/plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:39:in `resync_gitolite'
/opt/redmine/redmine261/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:49:in `resync_gitolite'
/opt/redmine/redmine261/plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:97:in `resync_gitolite'
/opt/redmine/redmine261/plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:15:in `destroy_ssh_key'
/opt/redmine/redmine261/plugins/redmine_git_hosting/lib/tasks/migration_tools.rake:56:in `block (4 levels) in <top (required)>'
/opt/redmine/redmine261/plugins/redmine_git_hosting/lib/tasks/migration_tools.rake:54:in `each'
/opt/redmine/redmine261/plugins/redmine_git_hosting/lib/tasks/migration_tools.rake:54:in `block (3 levels) in <top (required)>'
/opt/redmine/redmine261/plugins/redmine_git_hosting/lib/tasks/migration_tools.rake:115:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine_git_hosting:migration_tools:rename_ssh_keys
(See full trace by running task with --trace)
~~~
And if I browse my repositories from Redmine I have a 404 with this error message:

~~~
App 3621 stderr: fatal: Not a git repository: 'repositories/concertations.git'
~~~
Any fixes ?

**Comment by n-rodriguez** [comment]
as root :

```root$ apt-get install libssh2-1 libssh2-1-dev cmake libgpg-error-dev```

**Comment by n-rodriguez** [comment]
Then as Redmine user : ```bundle install --without development test```

**Comment by llaumgui** [comment]
Hi,

I have already install all of them...
