### ISSUE TITLE
Interfering with user profile

### ISSUE THREAD

**Issue by BAndonovski** [jbox-web/redmine_git_hosting#349]
This plugin seems to mess up the users view... 

Started GET "/redmine/users/6" for 192.168.122.1 at 2015-02-04 14:48:42 +0100
Processing by UsersController#show as HTML
  Parameters: {"id"=>"6"}
  Current user: r2d2 (id=6)
  Rendered plugins/redmine_git_hosting/app/views/users/show.api.rsb within layouts/base (40.4ms)
Completed 500 Internal Server Error in 405.3ms

ActionView::Template::Error (No builder for format ):
    1: api.user do
    2:   api.id         @user.id
    3:   api.login      @user.login if User.current.admin? || (User.current == @user)
    4:   api.firstname  @user.firstname
  lib/redmine/views/builders.rb:28:in `for'
  app/controllers/users_controller.rb:76:in `block (2 levels) in show'
  app/controllers/users_controller.rb:75:in `show'

**Comment by BAndonovski** [comment]
Found it's a duplicate of #331. Closing.
