### ISSUE TITLE
503 error on repository pages: 

### ISSUE THREAD

**Issue by anarcat** [jbox-web/redmine_git_hosting#352]
we have been having those errors for a while, probably after the squeeze to wheezy upgrade on this machine, which moved from gitolite 1.x to 2.x:

```
Started GET "/projects/X/repository" for Y at 2015-02-04 17:37:01 -0500
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"puppet-network"}
  Current user: Z (id=3)
git: error during get default branch: undefined method `[]' for nil:NilClass
The revision 'LICENSE' has a wrong format
The revision 'README' has a wrong format
The revision 'manifests' has a wrong format
The revision 'templates' has a wrong format
Completed 500 Internal Server Error in 411.0ms

TypeError (can't convert nil into String):
  lib/redmine/scm/adapters/git_adapter.rb:237:in `block (2 levels) in revisions'
  lib/redmine/scm/adapters/git_adapter.rb:226:in `block in revisions'
  lib/redmine/scm/adapters/git_adapter.rb:218:in `revisions'
  app/models/repository/git.rb:242:in `latest_changesets'
  app/controllers/repositories_controller.rb:122:in `show'
```

**Comment by anarcat** [comment]
it turns out this is because of spurious output in the ssh connexion. some banner is being printed by the server and making the scripts freak out. this is resolved the same way as #351 so i'll close and follow up there.
