### ISSUE TITLE
User profile can't be shown

### ISSUE THREAD

**Issue by saz** [jbox-web/redmine_git_hosting#365]
If I'm trying to open a user profile, I'm running into an ```Internal error```.

```
Started GET "/users/136" for [...IP...] at 2015-02-23 16:59:13 +0100
Processing by UsersController#show as HTML
  Parameters: {"id"=>"136"}
  Current user: saz (id=16)
  Rendered plugins/redmine_git_hosting/app/views/users/show.api.rsb within layouts/base (1.5ms)
Completed 500 Internal Server Error in 155.7ms

ActionView::Template::Error (No builder for format ):
    1: api.user do
    2:   api.id         @user.id
    3:   api.login      @user.login if User.current.admin? || (User.current == @user)
    4:   api.firstname  @user.firstname
  lib/redmine/views/builders.rb:28:in `for'
  app/controllers/users_controller.rb:76:in `block (2 levels) in show'
  app/controllers/users_controller.rb:75:in `show'
```

It looks like, as it is related to redmine_git_hosting, but I'm not entirely sure about that.

**Comment by carukc** [comment]
looks like this was reported while I was writing up my issue... I'm seeing the same problem... what can I do to help diagnose?

**Comment by n-rodriguez** [comment]
> what can I do to help diagnose?

Nothing :) Update the plugin : https://jbox-web.github.io/redmine_git_hosting/releases-notes/release-1.0.1.html

**Comment by carukc** [comment]
Thanks!  The update works well.

**Comment by saz** [comment]
Thank you! It's working now.
