### ISSUE TITLE
Rugged::NetworkError (This transport isn't implemented. Sorry)

### ISSUE THREAD

**Issue by henhof** [jbox-web/redmine_git_hosting#378]
Hi,
I have issues with create new repositories. I have checked these links but it doesn't helped me (https://github.com/jbox-web/redmine_git_hosting/issues/342 and https://github.com/jbox-web/redmine_git_hosting/issues/357).

In the Production log of Redmine I get this error:
```
Completed 500 Internal Server Error in 27.8ms

Rugged::NetworkError (This transport isn't implemented. Sorry):
  /home/redmine/.rvm/gems/ruby-2.1.4/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone_at'
  /home/redmine/.rvm/gems/ruby-2.1.4/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone'
  /home/redmine/.rvm/gems/ruby-2.1.4/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:110:in `initialize'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `new'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `gitolite_admin'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:38:in `resync_gitolite'
  plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:50:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:97:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:27:in `create_repository'
  plugins/redmine_git_hosting/app/use_cases/create_repository.rb:64:in `create_repository'
  plugins/redmine_git_hosting/app/use_cases/create_repository.rb:16:in `call'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:89:in `call_use_cases'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:46:in `create_with_git_hosting'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:502:in `_run__2858747219806737212__process_action__917347658096104349__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__1471549581984495806__call__1047822528274472179__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
  unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
  unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
  unicorn (4.8.3) bin/unicorn_rails:209:in `<top (required)>'
  /home/redmine/.rvm/gems/ruby-2.1.4/bin/unicorn_rails:23:in `load'
  /home/redmine/.rvm/gems/ruby-2.1.4/bin/unicorn_rails:23:in `<main>'
  /home/redmine/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
  /home/redmine/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

There is also an error with the Split of logs into multiple files. The folder doesn't create and after manually create, there are no files. The plugin used only the default logfile (REDMINE-ROOT/logs/git_hosting.log)

The set up is an fresh install of Centos7 with Redmine and git_hosting Plugin.
```Environment:
  Redmine version                2.6.2.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
  Xitolite                       1.8.3.1
Redmine plugins:
  redmine_bootstrap_kit          0.2.1
  redmine_ckeditor               1.0.20
  redmine_git_hosting            1.0.1
  redmine_ldap_sync              2.0.4.gde8e90cc03
  redmine_mylyn_connector        2.8.2.stable```

Under the config_test in the plugin page all is green.

I hope you can help, thanks for the great tool.

**Comment by henhof** [comment]
I have the feeling there is general a problem with the plugin on my system.
Cause I can't set any settings on the plugin page and the temp folder for "Temporary dir for lock file and data" (/tmp//tmp/redmine_git_hosting/) contains only the file structure until (/tmp/redmine_git_hosting/git/gitolite-admin.git).

In the production.log I see following message when I commit settings on the plugin page.
```
This transport isn't implemented. Sorry
Rugged::NetworkError (This transport isn't implemented. Sorry):
```

**Comment by n-rodriguez** [comment]
> Rugged::NetworkError (This transport isn't implemented. Sorry):

Are you sure you installed all the dependencies? 

Try to find this file : redmine$ /home/redmine/.rvm/gems/ruby-2.1.4/extensions/x86_64-linux/2.1.0/rugged-0.21.4/gem_make.out. It contains the compilation logs for Rugged. Check if there's any errors in it. (missing dependencies, things like that)

**Comment by n-rodriguez** [comment]
As root :

```
root# yum groupinstall "Development Tools"
root# yum install libssh2 libssh2-devel cmake libgpg-error-devel
```

Then as Redmine :

```
redmine$ cd REDMINE_ROOT
redmine$ gem uninstall gitolite-rugged
redmine$ bundle install --without development test
```

Restart Redmine.
