### ISSUE TITLE
500 error on project after adding repository on version 1.0.0

### ISSUE THREAD

**Issue by WMP** [jbox-web/redmine_git_hosting#394]
When i trying go to project page, i have 500 error and in logs i have:
```
Started GET "/projects/grodzina" for 77.255.235.245 at 2015-03-19 13:22:54 +0100
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"grodzina"}
  Current user: wmp (id=38)
  Rendered plugins/redmine_contacts/app/views/projects/_contacts.html.erb (1.4ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.erb (13.2ms)
  Rendered plugins/redmine_git_hosting/app/views/projects/_git_urls.html.haml (38.7ms)
  Rendered projects/show.html.erb within layouts/base (51.1ms)
Completed 500 Internal Server Error in 157.2ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: <% repositories = Array.wrap(repository) unless repositories %>
    2: <% if repositories.map(&:available_urls).flatten.reject { |m| m.blank? }.any? %>
    3:   <% repositories.sort_by { |r| r.is_default ? 0 : 1 }.each do |repository| %>
    4:     <% # Skip repository without URLs %>
    5:     <% next if repository.available_urls.empty? %>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/projects/show.html.erb:63:in `_app_views_projects_show_html_erb___74486739514800919_38840900'
  app/controllers/projects_controller.rb:163:in `show'
```

**Comment by n-rodriguez** [comment]
Hi!

Can you try with 1.0.3 version?

**Comment by n-rodriguez** [comment]
One (or many) of your repositories seem to not have an associated entry in GitExtra table.
How  to fix :
```
redmine$ cd <redmine root dir>/plugins/redmine_git_hosting
redmine$ git checkout v1.0.x
redmine$ cd <redmine root dir>
redmine$ bundle exec rake redmine_git_hosting:migrations_tools:check_git_extras_presence
```

**Comment by WMP** [comment]
```
redmine@redmine2:~/redmine$ bundle exec rake --trace redmine_git_hosting:migrations_tools:check_git_extras_presence
Your Gemfile lists the gem redcarpet (~> 2.3.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem vcard (~> 0.2.8) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
rake aborted!
Don't know how to build task 'redmine_git_hosting:migrations_tools:check_git_extras_presence'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/task_manager.rb:62:in `[]'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:149:in `invoke_task'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/redmine/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.1.1/bin/rake:23:in `load'
/home/redmine/.rvm/gems/ruby-2.1.1/bin/rake:23:in `<main>'
/home/redmine/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/home/redmine/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
redmine@redmine2:~/redmine$
````
