### ISSUE TITLE
Broken after reinstall of repositories

### ISSUE THREAD

**Issue by carukc** [jbox-web/redmine_git_hosting#412]
Hello,

I have managed to damage my git user account so rebuilt, recovered my repositories and reinstalled redmine_git_hosting.  In doing so I seem to have broken the repositories that had been connected to redmine.

Initially I could not even get to the configuration screen so I also updated from 1.0.2 to 1.0.3.  After the reinstall I ran the 'rescue tasks' and checked the config.  All seems good except for the  'Git user is able to sudo to Redmine user?' line.  It is marked by an explanation mark.  I might be wrong but the install instructions only seem to show how to give the redmine user access to git.  Should the config test be showing an error there?

Config test looks pretty clean but when I go to any page on a project with a repository I get and 'Internal Error'.

Have I messed something up in my database and if so can i repair or reset the database?

Logs enclosed.

Many Thanks
Chris

Debug Log
---------------
```
Started GET "/project/dev/pegasus-web" for at 2015-04-06 02:20:54 +0000
Processing by ProjectsController#show as HTML
  Parameters: {"section"=>"dev/pegasus-web"}
   (0.4ms)  SELECT MAX(`settings`.`updated_on`) AS max_id FROM `settings`
  User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 6 LIMIT 1
  Current user: quicksilver (id=6)
  Project Load (0.2ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'pegasus-web' LIMIT 1
  SQL (0.2ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 1
  ProjectSection Load (0.2ms)  SELECT `project_sections`.* FROM `project_sections` WHERE `project_sections`.`id` = 1 LIMIT 1
  ProjectSection Load (0.2ms)  SELECT `project_sections`.* FROM `project_sections` WHERE (`project_sections`.`lft` <= 7) AND (`project_sections`.`rgt` >= 8) ORDER BY `project_sections`.`lft`
  SQL (0.5ms)  SELECT `members`.`id` AS t0_r0, `members`.`user_id` AS t0_r1, `members`.`project_id` AS t0_r2, `members`.`created_on` AS t0_r3, `members`.`mail_notification` AS t0_r4, `members`.`dmsf_mail_notification` AS t0_r5, `users`.`id` AS t1_r0, `users`.`login` AS t1_r1, `users`.`hashed_password` AS t1_r2, `users`.`firstname` AS t1_r3, `users`.`lastname` AS t1_r4, `users`.`mail` AS t1_r5, `users`.`admin` AS t1_r6, `users`.`status` AS t1_r7, `users`.`last_login_on` AS t1_r8, `users`.`language` AS t1_r9, `users`.`auth_source_id` AS t1_r10, `users`.`created_on` AS t1_r11, `users`.`updated_on` AS t1_r12, `users`.`type` AS t1_r13, `users`.`identity_url` AS t1_r14, `users`.`mail_notification` AS t1_r15, `users`.`salt` AS t1_r16, `users`.`reminder_notification` AS t1_r17, `users`.`must_change_passwd` AS t1_r18, `users`.`passwd_changed_on` AS t1_r19, `roles`.`id` AS t2_r0, `roles`.`name` AS t2_r1, `roles`.`position` AS t2_r2, `roles`.`assignable` AS t2_r3, `roles`.`builtin` AS t2_r4, `roles`.`permissions` AS t2_r5, `roles`.`issues_visibility` AS t2_r6, `users_members`.`id` AS t3_r0, `users_members`.`login` AS t3_r1, `users_members`.`hashed_password` AS t3_r2, `users_members`.`firstname` AS t3_r3, `users_members`.`lastname` AS t3_r4, `users_members`.`mail` AS t3_r5, `users_members`.`admin` AS t3_r6, `users_members`.`status` AS t3_r7, `users_members`.`last_login_on` AS t3_r8, `users_members`.`language` AS t3_r9, `users_members`.`auth_source_id` AS t3_r10, `users_members`.`created_on` AS t3_r11, `users_members`.`updated_on` AS t3_r12, `users_members`.`type` AS t3_r13, `users_members`.`identity_url` AS t3_r14, `users_members`.`mail_notification` AS t3_r15, `users_members`.`salt` AS t3_r16, `users_members`.`reminder_notification` AS t3_r17, `users_members`.`must_change_passwd` AS t3_r18, `users_members`.`passwd_changed_on` AS t3_r19 FROM `members` LEFT OUTER JOIN `users` ON `users`.`id` = `members`.`user_id` LEFT OUTER JOIN `member_roles` ON `member_roles`.`member_id` = `members`.`id` LEFT OUTER JOIN `roles` ON `roles`.`id` = `member_roles`.`role_id` LEFT OUTER JOIN `users` `users_members` ON `users_members`.`id` = `members`.`user_id` AND `users_members`.`type` IN ('User', 'AnonymousUser') WHERE `members`.`project_id` = 1 AND (users.type='User' AND users.status=1)
  Project Load (0.3ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`parent_id` = 1 AND (projects.status <> 9) ORDER BY `lft`
  News Load (0.4ms)  SELECT `news`.* FROM `news` WHERE `news`.`project_id` = 1 ORDER BY news.created_on DESC LIMIT 5
  User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` IN (6, 8)
  Project Load (0.2ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`id` IN (1)
  Tracker Load (0.2ms)  SELECT DISTINCT trackers.* FROM `trackers` INNER JOIN `projects_trackers` ON `projects_trackers`.`tracker_id` = `trackers`.`id` INNER JOIN `projects` ON `projects`.`id` = `projects_trackers`.`project_id` JOIN enabled_modules ON enabled_modules.project_id = projects.id AND enabled_modules.name = 'issue_tracking' WHERE (projects.lft >= 6 AND projects.rgt <= 7 AND projects.status <> 9) ORDER BY trackers.position ASC
   (0.3ms)  SELECT COUNT(DISTINCT `issues`.`id`) AS count_id, tracker_id AS tracker_id FROM `issues` LEFT OUTER JOIN `projects` ON `projects`.`id` = `issues`.`project_id` LEFT OUTER JOIN `issue_statuses` ON `issue_statuses`.`id` = `issues`.`status_id` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking')) AND (issue_statuses.is_closed = 0) AND ((projects.id = 1 OR (projects.lft > 6 AND projects.rgt < 7))) GROUP BY tracker_id
  Tracker Load (0.2ms)  SELECT `trackers`.* FROM `trackers` WHERE `trackers`.`id` IN (1, 2, 3, 6)
   (0.2ms)  SELECT COUNT(DISTINCT `issues`.`id`) AS count_id, tracker_id AS tracker_id FROM `issues` LEFT OUTER JOIN `projects` ON `projects`.`id` = `issues`.`project_id` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking')) AND ((projects.id = 1 OR (projects.lft > 6 AND projects.rgt < 7))) GROUP BY tracker_id
  CACHE (0.0ms)  SELECT `trackers`.* FROM `trackers` WHERE `trackers`.`id` IN (1, 2, 3, 6)
   (0.2ms)  SELECT SUM(`time_entries`.`hours`) AS sum_id FROM `time_entries` LEFT OUTER JOIN `projects` ON `projects`.`id` = `time_entries`.`project_id` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='time_tracking')) AND ((projects.id = 1 OR (projects.lft > 6 AND projects.rgt < 7)))
  Token Load (0.2ms)  SELECT `tokens`.* FROM `tokens` WHERE `tokens`.`user_id` = 6 AND (action='feeds') LIMIT 1
  Version Load (0.2ms)  SELECT `versions`.* FROM `versions` WHERE `versions`.`project_id` = 1 ORDER BY versions.effective_date DESC, versions.name DESC
  CustomField Load (0.3ms)  SELECT `custom_fields`.* FROM `custom_fields` WHERE (type = 'ProjectCustomField') ORDER BY custom_fields.position ASC
  SQL (0.2ms)  SELECT `custom_values`.`id` AS t0_r0, `custom_values`.`customized_type` AS t0_r1, `custom_values`.`customized_id` AS t0_r2, `custom_values`.`custom_field_id` AS t0_r3, `custom_values`.`value` AS t0_r4, `custom_fields`.`id` AS t1_r0, `custom_fields`.`type` AS t1_r1, `custom_fields`.`name` AS t1_r2, `custom_fields`.`field_format` AS t1_r3, `custom_fields`.`possible_values` AS t1_r4, `custom_fields`.`regexp` AS t1_r5, `custom_fields`.`min_length` AS t1_r6, `custom_fields`.`max_length` AS t1_r7, `custom_fields`.`is_required` AS t1_r8, `custom_fields`.`is_for_all` AS t1_r9, `custom_fields`.`is_filter` AS t1_r10, `custom_fields`.`position` AS t1_r11, `custom_fields`.`searchable` AS t1_r12, `custom_fields`.`default_value` AS t1_r13, `custom_fields`.`editable` AS t1_r14, `custom_fields`.`visible` AS t1_r15, `custom_fields`.`multiple` AS t1_r16, `custom_fields`.`format_store` AS t1_r17, `custom_fields`.`description` AS t1_r18, `custom_fields`.`significant` AS t1_r19, `custom_fields`.`hint` AS t1_r20 FROM `custom_values` LEFT OUTER JOIN `custom_fields` ON `custom_fields`.`id` = `custom_values`.`custom_field_id` WHERE `custom_values`.`customized_id` = 1 AND `custom_values`.`customized_type` = 'Project' ORDER BY custom_fields.position
  Hook Load (0.2ms)  SELECT `hooks`.* FROM `hooks` WHERE `hooks`.`hook` = 'view_projects_show_left' LIMIT 1
  EnabledModule Load (0.2ms)  SELECT `enabled_modules`.* FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 1
  Repository Load (0.2ms)  SELECT `repositories`.* FROM `repositories` WHERE `repositories`.`project_id` = 1 AND (is_default = 1) LIMIT 1
   (0.2ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`project_id` = 1
  Repository Load (0.2ms)  SELECT `repositories`.* FROM `repositories` WHERE `repositories`.`project_id` = 1
  RepositoryGitExtra Load (0.3ms)  SELECT `repository_git_extras`.* FROM `repository_git_extras` WHERE `repository_git_extras`.`repository_id` = 21 LIMIT 1
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.erb (23.8ms)
  Rendered plugins/redmine_git_hosting/app/views/projects/_git_urls.html.haml (29.3ms)
  Rendered projects/show.html.erb within layouts/base (39.9ms)
Completed 500 Internal Server Error in 77.9ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: <% repositories = Array.wrap(repository) unless repositories %>
    2: <% if repositories.map(&:available_urls).flatten.reject { |m| m.blank? }.any? %>
    3:   <% repositories.sort_by { |r| r.is_default ? 0 : 1 }.each do |repository| %>
    4:     <% # Skip repository without URLs %>
    5:     <% next if repository.available_urls.empty? %>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/projects/show.html.erb:63:in `_app_views_projects_show_html_erb___2857667915095734592_65720680'
  app/controllers/projects_controller.rb:163:in `show'
```
Config
--------
```
Required Permissions

Temp directory writeable?	/tmp/redmine_git_hosting/git/gitolite-admin.git
Redmine username	app
Gitolite username	git
Git user is able to sudo to Redmine user?	Exclamation
Redmine user is able to sudo to Git user?	True
Hooks installed?	
Trueredmine_gitolite.rb
Truemail_notifications.py
Truegit_hosting_config.rb
Truegit_hosting_custom_hook.rb
Truegit_hosting_http_helper.rb
Truegit_hosting_post_receive.rb
Truegit_multimail.py
Hooks parameters installed?	
Trueredmineurl
Truedebugmode
Trueasyncmode
Mailer parameters installed?	
Truemailer
Trueenvironment
Truesmtpauth
Truesmtpserver
Truesmtpport
Truesmtpuser
Truesmtppass
Mirrors keys installed?	True
Git version	1.9.1
Gitolite version	3
Count of physical repositories in Gitolite	18
Gitolite banner
hello redmine_gitolite_admin_id_rsa, this is git@projects running gitolite3 v3.6.2-26-gf9c0008 on git 1.9.1

 R W	gitolite-admin
 R W	it-infrastructure/pegasus-web-j25
 R W	martingale/collector
 R W	martingale/hobbydb-sites/collector-fix
 R W	martingale/hobbydb-sites/collector-zoo-2-6-4
 R W	martingale/hobbydb-sites/joomla
 R W	martingale/hobbydb-sites/joomla-zoo-testapp
 R W	martingale/hobbydb-sites/lithium
 R W	martingale/hobbydb-sites/lithiumframework
 R W	martingale/hobbydb-sites/middletier
 R W	martingale/hobbydb-sites/puppet
 R W	martingale/toycollector
 R W	martingale/toycollector-sites/auctionworx
 R W	martingale/toycollector-sites/aw-global-config
 R W	martingale/toycollector-sites/mediawiki
 R W	martingale/toycollector-sites/support
 R W	pegasus-25
 R W	testing
PATH directories
/home/app/htdocs/projects/vendor/bundle/ruby/2.1.0/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
```

**Comment by n-rodriguez** [comment]
Update to v1.0.4 then :
```
root# su - redmine
redmine$ cd REDMINE_ROOT_DIR
redmine$ bundle exec rake redmine_git_hosting:migration_tools:check_git_extras_presence RAILS_ENV=production
```
