### ISSUE TITLE
Error when trying to add a new post receive URL 

### ISSUE THREAD

**Issue by florianBonavendi** [jbox-web/redmine_git_hosting#419]
I am running the latest redmine_git_hosting plugin on Redmine 2.6.3.
Everything works like a charm despite of that I cannot add a new post receive URL to a repository.

When trying to do so, the client does not react and on the server, a `undefined method 'split_payloads' for #<RepositoryPostReceiveUrl:0x00000008ad40a0>` error occurs.

Here are the details from the server logs:

```
Started GET "/repositories/62/post_receive_urls/new" for xxx.xxx.xxx.xxx at 2015-04-12 17:29:31 +0200
Processing by RepositoryPostReceiveUrlsController#new as */*
  Parameters: {"repository_id"=>"62"}
  Current user: theuser (id=3)
  Rendered plugins/redmine_git_hosting/app/views/repository_post_receive_urls/_form.html.haml (8.5ms)
  Rendered plugins/redmine_git_hosting/app/views/repository_post_receive_urls/new.html.haml (14.1ms)
Completed 500 Internal Server Error in 51.0ms

ActionView::Template::Error (undefined method `split_payloads' for #<RepositoryPostReceiveUrl:0x00000008ad40a0>):
    14:   %p= f.select :mode, [['Github-style POST', :github], ['Empty GET request', :get]], {}, onchange: "post_mode_change(this); return false;"
    15:
    16:   #payload_options{ style: @post_receive_url.github_mode? ? '' : 'display: none;' }
    17:     %p= f.check_box :split_payloads
    18:
    19:   - if @repository.branches.any?
    20:     %p= f.check_box :use_triggers, onchange: "trigger_mode_change(this); return false;"
  lib/redmine/views/labelled_form_builder.rb:34:in `check_box'
  app/helpers/application_helper.rb:1056:in `labelled_form_for'
```
Any ideas how to get this fixed?

Thanks!

**Comment by n-rodriguez** [comment]
Hi! What version of the plugin are you running?
It seems you forgot to run database migrations... http://redmine-git-hosting.io/how-to/migrate/
