### ISSUE TITLE
Error when trying to update user details

### ISSUE THREAD

**Issue by nedden** [jbox-web/redmine_git_hosting#430]
Hi! 

Here is log

```
Completed 500 Internal Server Error in 94ms (ActiveRecord: 3.6ms)

ActionView::Template::Error (undefined method `empty?' for nil:NilClass):
    4:
    5: <table class="list">
    6:
    7:   <% if ssh_keys.empty? %>
    8:     <tr>
    9:       <td>
   10:         <label><%= l(:label_no_public_keys) %></label>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__3486874287673849723_63662780'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__3486874287673849723_63662780'
  app/helpers/application_helper.rb:321:in `render_tabs'
  app/views/users/edit.html.erb:10:in `_app_views_users_edit_html_erb___416777007828736728_64232200'
  app/controllers/users_controller.rb:162:in `block (2 levels) in update'
  app/controllers/users_controller.rb:161:in `update'
```

Version:

```
Environment:
  Redmine version                3.0.2.stable
  Ruby version                   2.1.3-p242 (2014-09-19) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.9.5
  Filesystem                     
  Xitolite                       1.7.9.5
Redmine plugins:
  progressive_projects_list      2.0.1
  redmine_bootstrap_kit          0.2.3
  redmine_checklists             3.1.1
  redmine_git_hosting            1.0.4
  redmine_my_page_queries        2.1.6
  redmine_spent_time_in_issue_description 2.6
  redmine_youtube_video          1.0.0
```

**Comment by n-rodriguez** [comment]
Thank you!
