### ISSUE TITLE
Fetch changesets fails in mixed Git/SVN setup

### ISSUE THREAD

**Issue by ocanam** [jbox-web/redmine_git_hosting#442]
Setup:
- Redmine 2.5.2
- Gitolite 2
- Redmine Git Hosting v1.0.4
- SVN via Apache DAV-SVN

It seems the fetch changesets routine is lost when non-git repositories exist in the database.

Running `bundle exec rake redmine_git_hosting:fetch_changesets RAILS_ENV=production` fails with the error:
```
undefined method `git_cache_id' for #<Repository::Subversion:0x0000000661eee0>
```
The error occurs even when the cache is disabled in the plugin configuration.

Full trace
```
redmine:~$ bundle exec rake redmine_git_hosting:fetch_changesets RAILS_ENV=production --trace
[...not significants warnings...]
** Invoke redmine_git_hosting:fetch_changesets (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine_git_hosting:fetch_changesets
Performing manual fetch_changesets operation...
rake aborted!
undefined method `git_cache_id' for #<Repository::Subversion:0x0000000661eee0>
/var/lib/gems/1.9.1/gems/activemodel-3.2.19/lib/active_model/attribute_methods.rb:407:in `method_missing'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_methods.rb:149:in `method_missing'
/opt/redmine/plugins/redmine_git_hosting/app/models/concerns/gitolitable/cache.rb:18:in `repo_path_to_git_cache_id'
/opt/redmine/plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:525:in `git_cache_id'
/opt/redmine/plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:501:in `git_cmd'
/opt/redmine/plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:85:in `branches'
/opt/redmine/app/models/repository/git.rb:75:in `branches'
/opt/redmine/app/models/repository/git.rb:130:in `fetch_changesets'
/opt/redmine/app/models/repository.rb:342:in `block (2 levels) in fetch_changesets'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_proxy.rb:91:in `each'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_proxy.rb:91:in `method_missing'
/opt/redmine/app/models/repository.rb:340:in `block in fetch_changesets'
/opt/redmine/app/models/repository.rb:339:in `each'
/opt/redmine/app/models/repository.rb:339:in `fetch_changesets'
/opt/redmine/plugins/redmine_git_hosting/lib/tasks/redmine_git_hosting.rake:36:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine_git_hosting:fetch_changesets
```

**Comment by nicesw123** [comment]
Hi,

I'm using SVN und Redmine_Git_Hosting, and thinking of upgrading to Redmine_Git_Hosting 1.x

What does this bug mean? Is it only a problem for rake commands, or does it also have an influence during the normal running of redmine together with repositories?

For example: 
Question --> if I have set (under Administration->Settings->Repositories)
* "Fetch commits automatically" 
* "Enable WS for repository management"

... will this then also be affected?

Thanks.

**Comment by n-rodriguez** [comment]
@ocanam : I've done some tests and I can't reproduce this bug. But this is a weird bug because it says that ```Repository::SVN``` has no no method ```gitolite_cache_id``` but the repo is handled by the ```Repository::Git``` (```/opt/redmine/app/models/repository/git.rb:130:in `fetch_changesets') and then the ```Xitolite::Adapter``` (```/opt/redmine/plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:85:in `branches'```). This should not happen.

**Comment by n-rodriguez** [comment]
@nicesw123 

> For example:
> Question --> if I have set (under Administration->Settings->Repositories)
> 
>     "Fetch commits automatically"
>     "Enable WS for repository management"
> 
> ... will this then also be affected?

Normally no.

**Comment by ocanam** [comment]
FYI the problem didn't occur anymore since the migration of our redmine environment on a new server.

```
Debian 8.1 amd64
Apache2.4, with DAV-SVN

Environment:
  Redmine version                3.0.4.stable.14445
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.3
  redmine_ckeditor               1.1.0
  redmine_dmsf                   1.5.1 stable
  redmine_embedded               0.0.2
  redmine_git_hosting            1.1.1
  redmine_jenkins                1.0.1
  redmine_knowledgebase          3.0.7
  redmine_lightbox2              0.2.2
  redmine_per_project_formatting 0.0.4
```

**Comment by l337r007** [comment]
I could just reproduce this behaviour. It happens when a project has an SVN main repository and an additional Xitolite one.

```
Centos 7
Apache2.4, Passenger

Environment:
  Redmine version                2.6.9.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.22
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Mercurial                      2.6.2
  Git                            1.8.3.1
  Filesystem                     
  Xitolite                       1.8.3.1
Redmine plugins:
  redmine_backlogs               v1.0.6
  redmine_bootstrap_kit          0.2.3
  redmine_git_hosting            1.1.4
  redmine_ical                   thegcat-trunk
  redmine_scm                    0.5.0b
  redmine_sidekiq                2.1.0
```

**Comment by l337r007** [comment]
Addendum: Updating the changesets via hook does seem to work, irrespective of whether a main SVN repository is present.
My gut feeling is that this is not a redmine_git_hosting problem, but maybe Rails or Redmine. It looks like it might be fetching the repositories collection from the database using the wrong types when iterating over the whole collection.
