### ISSUE TITLE
500 errors on repository save

### ISSUE THREAD

**Issue by GuillaumeFromage** [jbox-web/redmine_git_hosting#473]
I use redmine_git_hosting version 1.1.0 with redmine 2.5.2.devel (debian packaged version).  The config test page is all green. I wonder if anyone has a clue about this.

When I try to save repository config I get:
```
Completed 200 OK in 41ms (Views: 12.1ms | ActiveRecord: 3.4ms)
Started PUT "/code/repositories/92" for 127.0.0.1 at 2015-07-01 15:13:26 -0700
Processing by RepositoriesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"6Pl7dvo5G4pCB+CDdswYeOmT5m6idBd3voTaL+DgLc8=", "repository"=>{"is_default"=>"1", "path_encoding"=>""}, "commit"=>"Save", "id"=>"92"}
  Current user: ASDF (id=666)
Redirected to https://asdf.asdf.asdf/code/projects/asdf/settings/repositories
Completed 500 Internal Server Error in 180ms (ActiveRecord: 18.3ms)

Rugged::ObjectError (Failed to create commit.):
  /var/lib/gems/2.1.0/bundler/gems/gitolite-rugged-85668adfb1f7/lib/gitolite/gitolite_admin.rb:284:in `create'
  /var/lib/gems/2.1.0/bundler/gems/gitolite-rugged-85668adfb1f7/lib/gitolite/gitolite_admin.rb:284:in `update'
  /var/lib/gems/2.1.0/bundler/gems/gitolite-rugged-85668adfb1f7/lib/gitolite/gitolite_admin.rb:107:in `initialize'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:71:in `new'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:71:in `gitolite_admin'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:39:in `resync_gitolite'
  plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:50:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:115:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:33:in `update_repository'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:91:in `call_use_cases'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:52:in `update_with_git_hosting'
  actionpack (4.1.10) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.10) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.10) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.10) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.10) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.10) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.10) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.10) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.10) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.10) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.10) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.10) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.10) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.10) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.10) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.10) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.10) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.10) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.10) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.10) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.10) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.10) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.10) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.10) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.10) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.1.10) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.10) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.10) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.10) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.10) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.10) lib/action_dispatch/routing/route_set.rb:692:in `call'
  /usr/lib/ruby/vendor_ruby/rack/openid.rb:98:in `call'
  rack (1.5.3) lib/rack/etag.rb:23:in `call'
  rack (1.5.3) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.3) lib/rack/head.rb:11:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.3) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.3) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.10) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.10) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.10) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.10) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.10) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.10) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.10) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.10) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.10) lib/rails/rack/logger.rb:20:in `call'
  /usr/lib/ruby/vendor_ruby/request_store/middleware.rb:8:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.3) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.3) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.10) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.3) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.10) lib/rails/engine.rb:514:in `call'
  railties (4.1.10) lib/rails/application.rb:144:in `call'
  railties (4.1.10) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.10) lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

```

**Comment by GuillaumeFromage** [comment]
The whole thing is pretty confusing at the exact time it says that it succeeded in the log:
[INFO] Installing Redmine Gitolite mirroring SSH keys ...
[INFO] Done!

And also, it doesn't do anything. The changes get added when I rake redmine_git_hosting:update_repositories, not when I save them. I'll keep digging.

**Comment by n-rodriguez** [comment]
> The whole thing is pretty confusing at the exact time it says that it succeeded in the log:
> [INFO] Installing Redmine Gitolite mirroring SSH keys ...
> [INFO] Done!

This has nothing to do.

**Comment by n-rodriguez** [comment]
> I'll keep digging.

Check that your Gitolite admin directory is not corrupted : 
``` 
# Do it as Redmine user to not break file permissions
root# su - redmine
redmine$ cd <path to gitolite admin temp dir>
redmine$ git fsck
```

**Comment by GuillaumeFromage** [comment]
Oh, sweet, thanks a lot, that fixed it !
