### ISSUE TITLE
Each version switching, my gitolite.conf not update

### ISSUE THREAD

**Issue by chadyred** [jbox-web/redmine_git_hosting#481]
Hi there,

every time I update, change version, I have the famous : 

```
2015-07-21 01:12:52 +0200 [INFO] User 'chadyred' created a new repository 'qsdauau'
2015-07-21 01:12:54 +0200 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/qsdauau.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
```

After a long time, I success to erase this but I switch from devel to 1.1.1 branch, and it's the same thing... I really suspect an error from git or ssh keys....

All function, but it seems that gitolite.conf is not update at all, because when I want to initiate a repositorie for a new project I have this error : 

```
FATAL: W any ahhh redmine_chadyred_5 DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

So that indicates that gitolite.conf is not up-to-date. 

Many thinks.
Good night !

**Comment by chadyred** [comment]
I investiguate a little more...

I reinstall gitolite with a new ssh key of redmine user. But nothing to do, the gitolite.conf is not update, and even if the repository is not created with a README I can't create it manually cause of the none update of permissions on "gitolite.conf" file. So my user don't have right on a new repositorie of a new project...which is not created at all...

Thanks!

**Comment by chadyred** [comment]
I just reinstall gitolite, all is good but always the same issue...

**Comment by chadyred** [comment]
Hey, my idea is that the 'git gc' to clean redmine cache is not enought executed so I execute it on the plugin, but not working.

THen I run a bundler install, this is my dependancies with your plugin : 

```
Using github-markup 1.3.3
Using gitlab-grack 2.0.0.pre from https://github.com/jbox-web/grack.git (at fix_rails4)
Using gratr19 0.4.4.1
Using rugged 0.22.2
Using gitolite-rugged 1.1.0 from https://github.com/jbox-web/gitolite-rugged.git (at 1.1.1)
```

**Comment by chadyred** [comment]
I try to clean bundle too with this command : 

```
root# su - redmine

redmine$ cd REDMINE_ROOT
redmine$ bundle clean --force
redmine$ bundle install --without development test
```

**Comment by chadyred** [comment]
So I all reinstall and it show that I have a last problem : 
in log of gitolite I have this when I create a repositorie automatically: 

```
2015-07-21 17:36:38 +0200 [INFO] User 'chadyred' created a new repository 'qsdaiuoi'
2015-07-21 17:36:39 +0200 [WARN] add_repository : repository 'qsdaiuoi' does not exist in Gitolite, create it ...
2015-07-21 17:36:39 +0200 [INFO] add_repository : commiting to Gitolite...
2015-07-21 17:36:39 +0200 [INFO] add_repository : let Gitolite create empty repository 'repositories/qsdaiuoi.git'
2015-07-21 17:36:42 +0200 [INFO] Execute Gitolite Plugins
2015-07-21 17:36:42 +0200 [INFO] Create README file for repository 'qsdaiuoi'
2015-07-21 17:36:42 +0200 [ERROR] Error while creating README file for repository 'qsdaiuoi'
2015-07-21 17:36:42 +0200 [ERROR] Failed to start SSH session: Failed getting banner

```

And when I create it manually I have this error : 

```
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Of course, I have add my ssh public key of my Linux user to the user in Redmine, and this last is a member on the project. He have all role and each role can manage repositories commit.

**Comment by n-rodriguez** [comment]
> FATAL: W any ahhh redmine_chadyred_5 DENIED by fallthru (or you mis-spelled the reponame) fatal: Could not read from remote repository.

It seems that the Gitolite Admin key is also used by chadyred user :  this must not happen.
Check for duplicate entries in ```<git user homedir>/.ssh/authorized_keys```file.

**Comment by chadyred** [comment]
Thanks for you reply, so I check and I see that the two keys are different. 

One of my user in my client host and one of the redmine user, which authorized throught git user.

In local, I have reinstall all and all is good but on production on the server, I have not all reinstall and I have the same error. I really want to cure this without reinstall all...It always seems that the gitolite.conf is not Synchroniste.

More information: 

```
redmine@mimoute:~$ ssh -i .ssh/redmine_gitolite_admin_id_rsa git@localhost info
hello redmine_gitolite_admin_id_rsa, this is git@mimoute running gitolite3 v3.6.3-10-g4be7ac5 on git 1.7.10.4

 R W	gitolite-admin
 R W	recette-etudiant-git
 R W	testing
redmine@mimoute:~$ ssh -i .ssh/redmine_gitolite_admin_id_rsa git@my-redmine.com info
hello redmine_gitolite_admin_id_rsa, this is git@mimoute running gitolite3 v3.6.3-10-g4be7ac5 on git 1.7.10.4

 R W	gitolite-admin
 R W	recette-etudiant-git
 R W	testing

```
You show that all works, but nothing about new project and I can't create manually repositories beacause of the *DENIED by fallthru*




For information, which that help a lot is the log of SSH in *"/var/log/auth.log"*. In locale I have this : 

```
Jul 22 10:32:36 cellier-Inspiron-5523 sshd[18982]: Accepted publickey for git from 127.0.0.1 port 57526 ssh2: RSA c6:59:07:b3:da:6b:b9:cf:c7:27:4d:1f:3c:2d:95:69
Jul 22 10:32:36 cellier-Inspiron-5523 sshd[18982]: pam_unix(sshd:session): session opened for user git by (uid=0)
Jul 22 10:32:36 cellier-Inspiron-5523 systemd-logind[999]: New session 128 of user git.
Jul 22 10:32:37 cellier-Inspiron-5523 sshd[18982]: pam_unix(sshd:session): session closed for user git
Jul 22 10:32:37 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c find /opt/gitolite/recycle_bin/ -type d -regex /opt/gitolite/recycle_bin/[0-9]+__qshj.git -prune -print
Jul 22 10:32:37 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:37 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:37 cellier-Inspiron-5523 sshd[19087]: Accepted publickey for git from 127.0.0.1 port 57528 ssh2: RSA c6:59:07:b3:da:6b:b9:cf:c7:27:4d:1f:3c:2d:95:69
Jul 22 10:32:37 cellier-Inspiron-5523 sshd[19087]: pam_unix(sshd:session): session opened for user git by (uid=0)
Jul 22 10:32:37 cellier-Inspiron-5523 systemd-logind[999]: Removed session 128.
Jul 22 10:32:37 cellier-Inspiron-5523 systemd-logind[999]: New session 129 of user git.
Jul 22 10:32:40 cellier-Inspiron-5523 sshd[19087]: pam_unix(sshd:session): session closed for user git
Jul 22 10:32:40 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c eval find /opt/gitolite/repositories/qshj.git/objects -type f | wc -l
Jul 22 10:32:40 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:40 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:40 cellier-Inspiron-5523 sshd[19640]: Accepted publickey for git from 127.0.0.1 port 57529 ssh2: RSA c6:59:07:b3:da:6b:b9:cf:c7:27:4d:1f:3c:2d:95:69
Jul 22 10:32:40 cellier-Inspiron-5523 sshd[19640]: pam_unix(sshd:session): session opened for user git by (uid=0)
Jul 22 10:32:40 cellier-Inspiron-5523 systemd-logind[999]: Removed session 129.
Jul 22 10:32:40 cellier-Inspiron-5523 systemd-logind[999]: New session 130 of user git.
Jul 22 10:32:40 cellier-Inspiron-5523 sshd[19640]: pam_unix(sshd:session): session closed for user git
Jul 22 10:32:40 cellier-Inspiron-5523 sshd[19684]: Accepted publickey for git from 127.0.0.1 port 57530 ssh2: RSA c6:59:07:b3:da:6b:b9:cf:c7:27:4d:1f:3c:2d:95:69
Jul 22 10:32:40 cellier-Inspiron-5523 sshd[19684]: pam_unix(sshd:session): session opened for user git by (uid=0)
Jul 22 10:32:40 cellier-Inspiron-5523 systemd-logind[999]: Removed session 130.
Jul 22 10:32:40 cellier-Inspiron-5523 systemd-logind[999]: New session 131 of user git.
Jul 22 10:32:41 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --version --no-color
Jul 22 10:32:41 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:41 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:41 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no branch --no-color --verbose --no-abbrev
Jul 22 10:32:41 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:41 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:41 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no log --no-color --encoding=UTF-8 --raw --date=iso --pretty=fuller --parents --stdin --reverse
Jul 22 10:32:41 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:41 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:41 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no rev-list --reverse 6c44f48fd41dc69a5c8d003f368899c1fe828461
Jul 22 10:32:41 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:41 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:42 cellier-Inspiron-5523 sshd[19684]: pam_unix(sshd:session): session closed for user git
Jul 22 10:32:42 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --version --no-color
Jul 22 10:32:42 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:42 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:44 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no ls-tree -l master:
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:44 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no log --no-color --encoding=UTF-8 --date=iso --pretty=fuller --no-merges -n 1 master -- README.md
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:44 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no log --no-color --encoding=UTF-8 --raw --date=iso --pretty=fuller --parents --stdin -n 10
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:44 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no tag
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:44 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no ls-tree -l HEAD:
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:44 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no log --no-color --encoding=UTF-8 --date=iso --pretty=fuller --no-merges -n 1 -- README.md
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:44 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
Jul 22 10:32:45 cellier-Inspiron-5523 sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qshj.git -c core.quotepath=false -c log.decorate=no show --no-color HEAD:README.md
Jul 22 10:32:45 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 10:32:45 cellier-Inspiron-5523 sudo: pam_unix(sudo:session): session closed for user git
```

and in production, in */var/log/auth.log* : 

```
Jul 22 11:17:19 mimoute sudo:  redmine : TTY=unknown ; PWD=/opt/redmine ; USER=git ; COMMAND=/bin/bash -c git --git-dir repositories/qnsdbqsqqq.git -c core.quotepath=false -c log.decorate=no branch --no-color --verbose --no-abbrev
Jul 22 11:17:19 mimoute sudo: pam_unix(sudo:session): session opened for user git by (uid=0)
Jul 22 11:17:19 mimoute sudo: pam_unix(sudo:session): session closed for user git
```

It's poor...I even disable my firewall, but nothing...

**Comment by chadyred** [comment]
So, so, so after a while I reinstall gitolite but nothing change, I remove your plugin completely and reinstall with: 

```
rake redmine:plugins:migrate NAME=redmine_git_hosting VERSION=0 RAILS_ENV=production
```

And redownload the git projet and reinstall : 

```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting
bundle install --without development test
```

And I all resync in the menu, allow auto README and all is good, but my project that I have created before have a log error in a controller : 

```
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"recette-etudiant"}
  Current user: chadyred (id=4)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.haml (50.8ms)
  Rendered plugins/redmine_git_hosting/app/views/projects/_git_urls.html.haml (1001.2ms)
  Rendered projects/show.html.erb within layouts/base (1062.6ms)
Completed 500 Internal Server Error in 2097ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    10:     $(document).ready(function() { setFirstGitUrl('.git_url_list'); setGitUrls('.git_url'); });
    11:
    12: - repositories = Array.wrap(repository) unless repositories
    13: - if repositories.map(&:available_urls_sorted).reject { |h| h.empty? }.any?
    14:   - repositories.sort_by { |r| r.is_default ? 0 : 1 }.each do |repository|
    15:     - next if repository.available_urls_sorted.empty?
    16:     - present repository do |p|
  lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in `map'
  lib/redmine/hook.rb:117:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/views/projects/show.html.erb:61:in `_app_views_projects_show_html_erb__4082529062210441362_70020475532080'
  app/controllers/projects_controller.rb:152:in `show'

```

Maybe a bug, but I think this is because I completely remove your plugin and maybe the database has lost data.

**Comment by n-rodriguez** [comment]
it seems that one of the repos doesn't have the git _extras relation sets.
Run  ```bundle exec rake redmine_git_hosting:migration_tools:check_git_extras_presence RAILS_ENV=production```
