### ISSUE TITLE
Migration path between redmine 2.3.4->3.1.0 and git hosting plugin 0.7.10->1.0.7

### ISSUE THREAD

**Issue by baby-gnu** [jbox-web/redmine_git_hosting#488]
Hello,

We have a 2.3.4 redmine installation and I'm testing the upgrade on a dedicated VM.

I managed to get redmine_git_hosting to version 0.7.10.

Now I'm blocked and I don't know how to solve it.

I first try to upgrade the plugin to version 1.0.7, but it fails:

```
redmine@redmine:/srv/redmine/prod$ bundle install --without development test rmagick
Fetching https://github.com/jbox-web/gitolite-rugged.git
Fetching https://github.com/jbox-web/grack.git
Fetching gem metadata from https://rubygems.org/........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "mocha":
  In Gemfile:
    shoulda (~> 3.3.2) ruby depends on
      shoulda-matchers (~> 1.4.1) ruby depends on
        bourne (~> 1.1.2) ruby depends on
          mocha (= 0.10.5) ruby

    mocha (0.13.3)

Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    gitlab-grack (>= 0) ruby depends on
      rack (~> 1.6.0) ruby

    rails (= 3.2.13) ruby depends on
      actionmailer (= 3.2.13) ruby depends on
        actionpack (= 3.2.13) ruby depends on
          rack (1.4.5)
```

If I try to migrate redmine first, I have the following

```
redmine@redmine:/srv/redmine/redmine-3.1.0$ bundle install --without development test rmagick
Please configure your config/database.yml first
You cannot specify the same gem twice with different version requirements.
You specified: redcarpet (~> 3.1.2) and redcarpet (~> 2.3.0)
```

3.1.2 is for redmine and 2.3.0 is for redmine_git_hosting.

Any idea?

Regards.

**Comment by baby-gnu** [comment]
I managed to get to redmine 2.6.6 with redmine_git_hosting 0.7.10.

I'll try to migrate both at the same time.

**Comment by n-rodriguez** [comment]
It seems that you are on the devel branch.
Be sure to checkout a stable branch. Otherwise check that development gems are commented in plugin's Gemfile. I know it's not the case for one of the releases. I don't remember which one. Sorry.

**Comment by n-rodriguez** [comment]
Any news?

**Comment by baby-gnu** [comment]
Sorry for the delay, I was on vacation ;-)

I checkout the tag, so I was on a detached head.

**Comment by baby-gnu** [comment]
Hello,

I decided to migrate my 2.3.4 on a more recent machine (Xenial) with ruby 2.3 and installing gems per redmine installation directory to avoid conflicts.

Unfortunately, I cannot upgrade 0.6.1 to 0.7.10, it may be due to more strict mysql 5.7:

```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.13/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
Migrating redmine_git_hosting (Redmine Git Hosting Plugin)...
==  CreateRepositoryGitConfigKeys: migrating ==================================
-- create_table(:repository_git_config_keys)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead: CREATE TABLE `repository_git_config_keys` (`id` int(11) DEFAULT NULL auto_increment PRIMARY KEY, `repository_id` int(11), `key` varchar(255), `value` varchar(255)) ENGINE=InnoDB
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/schema_statements.rb:170:in `create_table'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:434:in `create_table'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:466:in `block in method_missing'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `block in say_with_time'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `say_with_time'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:458:in `method_missing'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:334:in `method_missing'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/db/migrate/20140306002300_create_repository_git_config_keys.rb:4:in `up'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:370:in `up'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:410:in `block in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:389:in `migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in `migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:777:in `ddl_transaction'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:719:in `block in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `each'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:570:in `up'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:551:in `migrate'
/home/redmine/redmine-2.3.4/lib/redmine/plugin.rb:453:in `migrate_plugin'
/home/redmine/redmine-2.3.4/lib/redmine/plugin.rb:425:in `migrate'
/home/redmine/redmine-2.3.4/lib/redmine/plugin.rb:436:in `migrate'
/home/redmine/redmine-2.3.4/lib/tasks/redmine.rake:74:in `block (3 levels) in <top (required)>'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
ActiveRecord::StatementInvalid: Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead: CREATE TABLE `repository_git_config_keys` (`id` int(11) DEFAULT NULL auto_increment PRIMARY KEY, `repository_id` int(11), `key` varchar(255), `value` varchar(255)) ENGINE=InnoDB
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/schema_statements.rb:170:in `create_table'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:434:in `create_table'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:466:in `block in method_missing'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `block in say_with_time'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `say_with_time'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:458:in `method_missing'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:334:in `method_missing'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/db/migrate/20140306002300_create_repository_git_config_keys.rb:4:in `up'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:370:in `up'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:410:in `block in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:389:in `migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in `migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:777:in `ddl_transaction'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:719:in `block in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `each'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:570:in `up'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:551:in `migrate'
/home/redmine/redmine-2.3.4/lib/redmine/plugin.rb:453:in `migrate_plugin'
/home/redmine/redmine-2.3.4/lib/redmine/plugin.rb:425:in `migrate'
/home/redmine/redmine-2.3.4/lib/redmine/plugin.rb:436:in `migrate'
/home/redmine/redmine-2.3.4/lib/tasks/redmine.rake:74:in `block (3 levels) in <top (required)>'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/schema_statements.rb:170:in `create_table'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:434:in `create_table'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:466:in `block in method_missing'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `block in say_with_time'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `say_with_time'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:458:in `method_missing'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:334:in `method_missing'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/db/migrate/20140306002300_create_repository_git_config_keys.rb:4:in `up'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:370:in `up'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:410:in `block in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:389:in `migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in `migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:777:in `ddl_transaction'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:719:in `block in migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `each'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `migrate'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:570:in `up'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.13/lib/active_record/migration.rb:551:in `migrate'
/home/redmine/redmine-2.3.4/lib/redmine/plugin.rb:453:in `migrate_plugin'
/home/redmine/redmine-2.3.4/lib/redmine/plugin.rb:425:in `migrate'
/home/redmine/redmine-2.3.4/lib/redmine/plugin.rb:436:in `migrate'
/home/redmine/redmine-2.3.4/lib/tasks/redmine.rake:74:in `block (3 levels) in <top (required)>'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by baby-gnu** [comment]
I tried the following upgrade path:

* production server is on Debian Weezy
* on Debian jessie:
** replicate the redmine from the production server
** upgrade redmine_git_hosting to 0.7.10
** rename_ssh_keys => error:
```
bundle exec rake --trace redmine_git_hosting:rename_ssh_keys RAILS_ENV=production
Your Gemfile lists the gem nokogiri (< 1.6.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem thin (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
** Invoke redmine_git_hosting:rename_ssh_keys (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine_git_hosting:rename_ssh_keys

Delete SSH keys in Gitolite and reset identifier :

  - Delete SSH key redmine_eolepack_1393415509_779488
rake aborted!
NoMethodError: undefined method `ssh_keys' for nil:NilClass
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users_helper.rb:49:in `remove_inactive_key'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users_helper.rb:12:in `handle_ssh_key_delete'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users.rb:45:in `block in delete_ssh_keys'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:179:in `block in wrapped_transaction'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:164:in `block in get_lock'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:159:in `open'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:159:in `get_lock'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:176:in `wrapped_transaction'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users.rb:44:in `delete_ssh_keys'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users.rb:22:in `delete_ssh_key'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/shell.rb:66:in `handle_command'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/redmine_gitolite/git_hosting.rb:44:in `resync_gitolite'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/tasks/rename_ssh_keys.rake:18:in `block (3 levels) in <top (required)>'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.13/lib/active_record/relation/delegation.rb:6:in `each'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.13/lib/active_record/relation/delegation.rb:6:in `each'
/home/redmine/redmine-2.3.4/plugins/redmine_git_hosting/lib/tasks/rename_ssh_keys.rake:10:in `block (2 levels) in <top (required)>'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `call'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/redmine/redmine-2.3.4/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => redmine_git_hosting:rename_ssh_keys
```

Any idea?

Regards.

**Comment by baby-gnu** [comment]
> bundle exec rake --trace redmine_git_hosting:rename_ssh_keys RAILS_ENV=production
> Your Gemfile lists the gem nokogiri (< 1.6.0) more than once.
> You should probably keep only one of them.
> While it's not a problem now, it could cause errors if you change the version of just one of them later.
> Your Gemfile lists the gem thin (>= 0) more than once.
> You should probably keep only one of them.
> While it's not a problem now, it could cause errors if you change the version of just one of them later.
> ** Invoke redmine_git_hosting:rename_ssh_keys (first_time)
> ** Invoke environment (first_time)
> ** Execute environment
> ** Execute redmine_git_hosting:rename_ssh_keys
> 
> Delete SSH keys in Gitolite and reset identifier :
> 
>   - Delete SSH key redmine_eolepack_1393415509_779488
> rake aborted!
> NoMethodError: undefined method `ssh_keys' for nil:NilClass

This error was caused by the fail of cloning the `gitolite-admin` repository.

**Comment by baby-gnu** [comment]
I managed to make my migration from 0.6.3 using a Debian Jessie intermediate machine to upgrade `redmine_git_hosting` to version 0.7.10:

- rsync my redmine 2.3.4 from my prod server

- dump/restore my 2.3.4 DB from my prod server

- rsync my git home dir from my prod server

- upgrade my gitolite for OpenSSH 6.8 compat (sitaramc/gitolite@ed807a40c6683960e357bc995b3acf721ec088b4)

- start redmine to check that everything was working correctly

- apply #619

- follow [the migration from 0.6 to 0.7.10](http://redmine-git-hosting.io/how-to/migrate/#step-by-step-migration-from-06-version-or-older-to-v0710)

- start redmine and check that everything was working correctly

The migration from redmine 2.3.4 with `redmine_git_hosting` 0.7.10 on the intermediate VM to the target machine (Ubuntu Xenial) with redmine 3.3.0 with `redmine_git_hosting` 1.2.1:

- prepare a redmine 3.3.0 on the target

- run `bundle exec rake redmine_git_hosting:prepare_migration_to_v1 RAILS_ENV=production` on the intermediate machine

- rsync my redmine datas (`files/`) to the target `/home/redmine/redmine-3.3.0/files/`

- dump/restore my 2.3.4 DB from my intermediate server to the target

- delete duplicated entries in DB

```sql
DELETE FROM repository_git_extras USING repository_git_extras, repository_git_extras r1 WHERE repository_git_extras.id > r1.id AND repository_git_extras.repository_id = r1.repository_id;
```

- rsync my git home dir from my intermediate server to the target

- populate `~redmine/.ssh/known_hosts`

- configure sudo

```
cat > /etc/sudoers.d/redmine <<'EOF'
Defaults:redmine !requiretty
redmine ALL=(git) NOPASSWD:ALL
EOF
```

- then I follow [the migration from 0.7.x to 1.x](http://redmine-git-hosting.io/how-to/migrate/#step-by-step-migration-from-07x-version-to-1x)

Now except #568 everything is running fine.

Regards.
