### ISSUE TITLE
"Unable to autoload constant Journal" fail when code files are changed

### ISSUE THREAD

**Issue by eduardobogoni** [jbox-web/redmine_git_hosting#494]
I'm using Redmine 3.1.0 and Redmine Git Hosting Plugin 1.1.1 and it is working normally. However, when the application is started in development mode (`rais s -e development`) and any file is changed (Ex.: adding empty spaces at end of `/app/controllers/account_controller.rb`) this error occurs:

```
I, [2015-08-13T13:50:03.926875 #16568]  INFO -- : Started GET "/" for 127.0.0.1 at 2015-08-13 13:50:03 -0300
F, [2015-08-13T13:50:04.130938 #16568] FATAL -- : 
LoadError (Unable to autoload constant Journal, expected /home/eduardo/redmine/app/models/journal.rb to define it):
  activesupport (4.2.3) lib/active_support/dependencies.rb:495:in `load_missing_constant'
  activesupport (4.2.3) lib/active_support/dependencies.rb:184:in `const_missing'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/journal_patch.rb:19:in `<top (required)>'
  activesupport (4.2.3) lib/active_support/dependencies.rb:457:in `load'
  activesupport (4.2.3) lib/active_support/dependencies.rb:457:in `block in load_file'
  activesupport (4.2.3) lib/active_support/dependencies.rb:647:in `new_constants_in'
  activesupport (4.2.3) lib/active_support/dependencies.rb:456:in `load_file'
  activesupport (4.2.3) lib/active_support/dependencies.rb:354:in `require_or_load'
  activesupport (4.2.3) lib/active_support/dependencies.rb:317:in `depend_on'
  activesupport (4.2.3) lib/active_support/dependencies.rb:233:in `require_dependency'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/redmine_plugin_loader.rb:70:in `block in autoload_libs!'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/redmine_plugin_loader.rb:68:in `each'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/redmine_plugin_loader.rb:68:in `autoload_libs!'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/redmine_plugin_loader.rb:61:in `load_plugin!'
  plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:57:in `block in <top (required)>'
  activesupport (4.2.3) lib/active_support/callbacks.rb:444:in `instance_exec'
  activesupport (4.2.3) lib/active_support/callbacks.rb:444:in `block in make_lambda'
  activesupport (4.2.3) lib/active_support/callbacks.rb:190:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:190:in `block in simple'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `each'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:71:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:22:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /home/eduardo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /home/eduardo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /home/eduardo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```
This error does not occur if `redmine_git_hosting` is not in `plugins` directory.
If the server is restarted the error message is vanished (Until tne next code file change).

**Comment by n-rodriguez** [comment]
Hi! Yes. I know this bug. Need to investigate.

**Comment by n-rodriguez** [comment]
Actually it seems that it's a Rails bug : http://www.redmine.org/issues/20513 https://github.com/rails/rails/issues/21198

**Comment by n-rodriguez** [comment]
I close it since I can't do anything at this level. This must be fixed in Rails or at least in Redmine.
