### ISSUE TITLE
plugin installation issue github-markup

### ISSUE THREAD

**Issue by Cyancaly** [jbox-web/redmine_git_hosting#497]
Im currently trying to migrate our redmine from an old version (1.4.4) to 3.02.

After installing and migrating all necessary databases etc. I"m trying to install redmine_git_hosting following the getting started documentation.

```
redmine@test123:REDMINE_ROOT#:bundle install --without development test
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.1.12
Using builder 3.2.2
Using erubis 2.7.0
Using actionview 4.1.12
Using rack 1.5.5
Using rack-test 0.6.3
Using actionpack 4.1.12
Using mime-types 2.6.1
Using mail 2.6.3
Using actionmailer 4.1.12
Using actionpack-action_caching 1.1.1
Using activemodel 4.1.12
Using arel 5.0.1.20140414130214
Using activerecord 4.1.12
Using awesome_nested_set 3.0.2
Using bundler 1.7.4
Using coderay 1.1.0
Using thor 0.19.1
Using railties 4.1.12
Using jquery-rails 3.1.3
Using net-ldap 0.11
Using pg 0.18.2
Using protected_attributes 1.1.3
Using ruby-openid 2.7.0
Using rack-openid 1.4.2
Using sprockets 3.3.1
Using sprockets-rails 2.3.2
Using rails 4.1.12
Using redcarpet 3.1.2
Using request_store 1.2.0
Using rmagick 2.15.4
Your bundle is complete!
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```
Looking fine so far, no error messages \0/.

but when I try to 
```
redmine@test123:REDMINE_ROOT# exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting --trace
```

my ssh session gets dropped after I get the following error message

```
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
rake aborted!
LoadError: cannot load such file -- github/markup
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/usr/share/redmine/lib/plugins/redmine_git_hosting/lib/redmine_git_hosting/hooks/display_repository_readme.rb:1:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/usr/share/redmine/lib/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:7:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/usr/share/redmine/lib/plugins/redmine_git_hosting/init.rb:5:in `block in <top (required)>'
/usr/share/redmine/config/initializers/00-core_plugins.rb:12:in `eval'
/usr/share/redmine/config/initializers/00-core_plugins.rb:12:in `block in <top (required)>'
/usr/share/redmine/config/initializers/00-core_plugins.rb:2:in `each'
/usr/share/redmine/config/initializers/00-core_plugins.rb:2:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:648:in `block in load_config_initializer'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/notifications.rb:161:in `instrument'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:647:in `load_config_initializer'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:611:in `each'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:611:in `block in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'
/var/lib/gems/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
Connection to test123 closed.
```

I did NOT edit the Gemfile in REDMINE_ROOT/lib/plugin/redmine_git_hosting/ because I'm using Redmine 3.x which is already uncommented while Redmine 2.x is commented

```
source 'https://rubygems.org'

# Gitolite Admin repository management
gem 'gitolite-rugged', git: 'https://github.com/jbox-web/gitolite-rugged.git', tag: '1.1.1'

## Redmine 3.x
## Ruby/Rack Git Smart-HTTP Server Handler (use our own repository because Redmine uses Rails 4.2 and Rack 1.6)
gem 'gitlab-grack', git: 'https://github.com/jbox-web/grack.git', require: 'grack', branch: 'fix_rails4'
gem 'redcarpet', '~> 3.1.2'

## Redmine 2.x
## Ruby/Rack Git Smart-HTTP Server Handler (use our own repository because Redmine still uses Rails 3 and Rack 1.4)
# gem 'gitlab-grack', git: 'https://github.com/jbox-web/grack.git', require: 'grack', branch: 'fix_rails3'
# gem 'redcarpet', '~> 2.3.0'

# HAML views
gem 'haml-rails'

# Memcached client for GitCache
gem 'dalli'

# Redis client for GitCache
gem 'redis'
gem 'hiredis'

# Syntaxic coloration
gem 'github-markup'
gem 'RedCloth'
gem 'org-ruby'
gem 'creole'
# gem 'wikicloth'
gem 'asciidoctor'

# group :development, :test do
#   gem 'rspec', '~> 3.0.0'
#   gem 'rspec-rails', '~> 3.0.1'

#   gem 'shoulda', '~> 3.5.0'
#   gem 'shoulda-matchers', '~> 2.7.0'
#   gem 'shoulda-context'

#   gem 'factory_girl'
#   gem 'factory_girl_rails'
#   gem 'faker'
#   gem 'database_cleaner'

#   # Code coverage
#   gem 'simplecov', '~> 0.9.1'
#   gem 'simplecov-rcov'

#   # Junit results
#   gem 'ci_reporter_rspec', '~> 1.0.0'

#   # Publish to Coveralls
#   gem 'coveralls', require: false

#   # Publish to CodeClimate
#   gem 'codeclimate-test-reporter', require: false
# end
```

looing thrugh your issues and asking google told me that maybe a gem is missing in my installation (github-markup).

I tried reinstalling redmine from scratch 2 times already.

Im using a debian Jessie, ruby 2.1.

btw: dropping my ssh session after that rake failure is really annoying

Maybe someone is able to help me out here :)

greetings,

**Comment by n-rodriguez** [comment]
You must do ```bundle exec``` and not ```exec```

**Comment by Cyancaly** [comment]
*facepalm* ough. did it again, this time i made sure i did it right.
getting another error now, 
```
redmine@test123:/usr/share/redmine# bundle install --without development test
Your Gemfile lists the gem redcarpet (~> 3.1.2) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Updating https://github.com/jbox-web/gitolite-rugged.git
Updating https://github.com/jbox-web/grack.git
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 4.1.4) ruby depends on
      actionpack (= 4.1.4) ruby depends on
        rack (~> 1.5.2) ruby

    gitlab-grack (>= 0) ruby depends on
      rack (1.6.0
```

I found your answer in #429 did both things - deleted Gemfile.lock. I don't need to comment/uncomment anything in the Gemfile becaue I'm using Redmine 3.x which is alreadz uncommented.

Any further ideas?

Thanks so far :)

**Comment by n-rodriguez** [comment]
What version of Redmine are you running? This is weird because I see rails 4.1.4 in your ouput whereas Redmine use rails 4.2.

**Comment by n-rodriguez** [comment]
Ok. Is it the Debian Jessie package?

**Comment by Cyancaly** [comment]
Yes it is the debian jessie package

**Comment by n-rodriguez** [comment]
I guess that's why it's using rails 4.1 instead of rails 4.2.

**Comment by n-rodriguez** [comment]
In plugin's Gemfile change the grack repo to : https://github.com/gitlabhq/grack.git.
It should pass as they also use rails 4.1.

**Comment by Cyancaly** [comment]
will try this later the day :) Thanks

**Comment by Cyancaly** [comment]
Did it just now. after recieving an error which told me

```
fatal: ambiguous argument 'fix_rails4': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Git error: command `git rev-parse fix_rails4` in directory /var/lib/gems/2.1.0/cache/bundler/git/grack-8ecd9f643cfb6a2df1fbbbb053038ca8312a02a3 has failed.
If this error persists you could try removing the cache directory '/var/lib/gems/2.1.0/cache/bundler/git/grack-8ecd9f643cfb6a2df1fbbbb053038ca8312a02a3'
```

I replaced
```
branch: 'fix_rails3'
```
with

```
branch: 'master'
```
and everthings working now.

Thank you very much  for your help :)

Simon
