### ISSUE TITLE
Redmine upgraded redcarpet gem to 3.3.2

### ISSUE THREAD

**Issue by fcanovai** [jbox-web/redmine_git_hosting#510]
Redmine has upgraded its dependency on redcarpet 3.3.2 in its stable branches (2.6, 3.0, 3.1). This cause the following conflict while running bundle install: 
````
$bundle install --gemfile=redmine-3.0/Gemfile  --without development,test,mysql,sqlite
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.

[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: redcarpet (~> 3.3.2) and redcarpet (~> 3.1.2). Bundler cannot continue.

 #  from /srv/redmine/redmine-3.0/plugins/redmine_git_hosting/Gemfile:9
 #  -------------------------------------------
 #  gem 'gitlab-grack', git: 'https://github.com/jbox-web/grack.git', require: 'grack', branch: 'fix_rails4'
 >  gem 'redcarpet', '~> 3.1.2'
 #  
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /srv/redmine/redmine-3.0/Gemfile:109
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------
````

**Comment by n-rodriguez** [comment]
I know :) https://travis-ci.org/jbox-web/redmine_git_hosting/jobs/8011228. The Gemfile will be updated when new Redmine versions will be released.
Thank you!

**Comment by piwats** [comment]
Version 3.1.1 was released on 20th of September.

I"m trying to install the git_hosting plugin. I see this error, which is a little bit frustrating, since changing the version in that specific Gemfile seems to break completely everything. (I am getting errors like LoadError blablabla rdoc...)

**Comment by n-rodriguez** [comment]
@piwats : can you provide some logs because it's working : https://travis-ci.org/jbox-web/redmine_git_hosting/jobs/81474345

**Comment by piwats** [comment]
I'm using the install guide. Redmine is 3.1.1.

Steps before the error:
1.) I clone and checkout the Bootstrap Kit and the Git hosting plugin as said in the docs/starting guide.
2.) I run the bundle install ....
3.) I do the db migration thing, which gives me this error:
```
redmine@bobo ~/redmine $ bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: cannot load such file -- rdoc
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/redmine/.gem/ruby/2.1.0/gems/github-markup-1.4.0/lib/github/markup/rdoc.rb:2:in `<top (required)>'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/redmine/.gem/ruby/2.1.0/gems/github-markup-1.4.0/lib/github/markups.rb:2:in `<module:Markup>'
/var/redmine/.gem/ruby/2.1.0/gems/github-markup-1.4.0/lib/github/markup.rb:53:in `instance_eval'
/var/redmine/.gem/ruby/2.1.0/gems/github-markup-1.4.0/lib/github/markup.rb:53:in `<module:Markup>'
/var/redmine/.gem/ruby/2.1.0/gems/github-markup-1.4.0/lib/github/markup.rb:5:in `<module:GitHub>'
/var/redmine/.gem/ruby/2.1.0/gems/github-markup-1.4.0/lib/github/markup.rb:4:in `<top (required)>'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/redmine/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/hooks/display_repository_readme.rb:1:in `<top (required)>'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/redmine/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:7:in `<top (required)>'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/redmine/redmine/plugins/redmine_git_hosting/init.rb:5:in `<top (required)>'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/redmine/redmine/lib/redmine/plugin.rb:155:in `block in load'
/var/redmine/redmine/lib/redmine/plugin.rb:146:in `each'
/var/redmine/redmine/lib/redmine/plugin.rb:146:in `load'
/var/redmine/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib64/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/lib64/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/lib64/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib64/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/lib64/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib64/ruby/2.1.0/tsort.rb:411:in `call'
/usr/lib64/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/usr/lib64/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/lib64/ruby/2.1.0/tsort.rb:345:in `each'
/usr/lib64/ruby/2.1.0/tsort.rb:345:in `call'
/usr/lib64/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/lib64/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/lib64/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/var/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/bin/rake:9:in `load'
/usr/bin/rake:9:in `<main>'
Polyglot::PolyglotLoadError: Failed to load /var/redmine/redmine/config/environment.rb using extensions rb
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:55:in `load'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:68:in `rescue in require'
/var/redmine/.gem/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/usr/lib64/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/bin/rake:9:in `load'
/usr/bin/rake:9:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

So, did I miss something?
Thanks in advance.

**Comment by n-rodriguez** [comment]
Add ```gem rdoc``` in ```# Syntaxic coloration``` section and do a ```bundle update``` and retry.

**Comment by piwats** [comment]
There is a conflict now:

```
[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rdoc (>= 2.4.2) and rdoc (>= 0). Bundler cannot continue.

 #  from /var/redmine/redmine/plugins/redmine_git_hosting/Gemfile:33
 #  -------------------------------------------
 #  gem 'asciidoctor'
 >  gem 'rdoc'
 #  
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /var/redmine/redmine/Gemfile:110
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------
```

**Comment by n-rodriguez** [comment]
```gem 'rdoc', '~> 2.4.2'```

**Comment by piwats** [comment]
This gives the same kind of error:
```
[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rdoc (>= 2.4.2) and rdoc (~> 2.4.2). Bundler cannot continue.

 #  from /var/redmine/redmine/plugins/redmine_git_hosting/Gemfile:33
 #  -------------------------------------------
 #  gem 'asciidoctor'
 >  gem 'rdoc', '~> 2.4.2'
 #  
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /var/redmine/redmine/Gemfile:110
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------
```

I think, I figured out where the problem is.

I did a fresh install of redmine today, step by step as it is stated in their docs.

rdoc is inside the development group, which is left out when following the redmine docs by installig the production env.

I put rdoc in Gemfile.local, migration worked.

**Comment by n-rodriguez** [comment]
> I put rdoc in Gemfile.local, migration worked.

Great :)

**Comment by decibel83** [comment]
Hi,
I'm having the same problem installing the 1.1.4 version on Redmine 3.0.5:

```
redmine@dev:~/redmine$ bundle install --without development test postgresql sqlite
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.

[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: redcarpet (~> 3.3.2) and redcarpet (~> 3.1.2). Bundler cannot continue.

 #  from /opt/redmine/redmine-3.0.5/plugins/redmine_git_hosting/Gemfile:9
 #  -------------------------------------------
 #  gem 'gitlab-grack', git: 'https://github.com/jbox-web/grack.git', require: 'grack', branch: 'fix_rails4'
 >  gem 'redcarpet', '~> 3.1.2'
 #  
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /opt/redmine/redmine-3.0.5/Gemfile:109
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------
```

I know you are working on this issue, but could you help me to manually fix it without waiting for the bugfix?

Thank you very much!

**Comment by n-rodriguez** [comment]
@decibel83 replace ```3.1.2``` by ```3.3.2``` in plugin's Gemfile.
