### ISSUE TITLE
error with sudo

### ISSUE THREAD

**Issue by grawerpl** [jbox-web/redmine_git_hosting#527]
i have problem witch plugin ant this may be problem witch security but who knows.
my configuration:
```
Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux-gnu]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               mysql2
SCM:
  Git                            2.6.2-0ppa1
  Filesystem
  Xitolite                       (because of error - see log below - redmine cant get version :D) 
Redmine plugins:
  redmine_bootstrap_kit          0.2.3
  redmine_git_hosting            1.1.4

Sudo version is 1.8.9p5
Ubuntu Server Trusty 14.04.3 LST (custom kernel 4.1.7 + grsec) 
Gitolite v3.6.3-11-g2417156
```
Yes i have checked my config few times and still can't find what is wrong (ruby is not my favorite language)

in __production.log__ i have this
```
Started GET "/settings/plugin/redmine_git_hosting" for 78.10.106.235 at 2015-10-27 20:46:33 +0100
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_git_hosting"}
  Current user: bolek (id=7)
  Rendered plugins/redmine_bootstrap_kit/app/views/common/_modal_base.html.haml (42.4ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_hosting_js_headers.html.haml (48.1ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_ssh.html.haml (3.6ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_storage.html.haml (11.5ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_file.html.haml (6.6ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_global.html.haml (6.3ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_access.html.haml (16.2ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_hooks.html.haml (9.3ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_cache.html.haml (3.9ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_notify.html.haml (5.6ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_display_access.html.haml (7.4ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_redmine_config.html.haml (13.5ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_sidekiq_interface.html.haml (1.7ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_test.html.haml (16.3ms)
  Rendered common/_tabs.html.erb (110.9ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.haml (164.8ms)
  Rendered settings/plugin.html.erb within layouts/admin (199.0ms)
Completed 500 Internal Server Error in 255ms (ActiveRecord: 4.8ms)

ActionView::Template::Error (undefined method `chomp' for nil:NilClass):
     9:   %tr
    10:     %td= l(:label_redmine_user)
    11:     %td
    12:       %span{ class: 'label label-success' }= RedmineGitHosting::Config.redmine_user
    13:
    14:   %tr
    15:     %td= l(:label_gitolite_user)
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__3850386775423715105_44023020'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__3850386775423715105_44023020'
  app/helpers/application_helper.rb:322:in `render_tabs'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___1984449867091835800_35549240'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___1984449867091835800_35549240'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
in __git_hosting.log__ have this:
```
2015-10-27 19:59:27 +0100 [INFO] Resync all projects (1)...
2015-10-27 19:59:27 +0100 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-10-27 19:59:27 +0100 [ERROR] Access denied for Gitolite Admin SSH Keys
2015-10-27 19:59:27 +0100 [ERROR] Unsupported URL protocol
2015-10-27 20:00:26 +0100 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-10-27 20:00:26 +0100 [INFO] Create tmp directory : '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-10-27 20:10:08 +0100 [ERROR] Can't retrieve Git version: Exception occured executing `sudo -n -u git -i /usr/bin/git --version --no-color` : No such file or directory - sudo
2015-10-27 20:11:14 +0100 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
```

**Comment by derats** [comment]
You problem is
2015-10-27 19:59:27 +0100 [ERROR] Access denied for Gitolite Admin SSH Keys
Generate and correctly configure ssh keys

**Comment by grawerpl** [comment]
ok i thunked that same but then i foud that if i try
```
ssh git@localhost info
hello redmine_gitolite_admin_id_rsa, this is git@localhost running gitolite3 v3.6.3-11-g2417156 on git 2.6.2
    R W  gitolite-admin
    R W  testing
```
i got info of repository like should be so this is not a ssh key problem especially that plugin copy key from ssh_keys placed inside app dir

**Comment by derats** [comment]
How about first tab on plugin setting, all parameters correct?

**Comment by grawerpl** [comment]
i cant even get there. Every time i try redmine return 500 and in log i have what is present in first post. production.log.
today i changed kernel to 4.2.5 without grsec but still that same error (everything expect plugin work fine).
```
root@seraphim:~# su - redmine
redmine@seraphim:~$ ssh git@localhost
PTY allocation request failed on channel 0
hello redmine_gitolite_admin_id_rsa, this is git@seraphim running gitolite3 v3.6.3-11-g2417156 on git 2.6.2

 R W    gitolite-admin
 R W    testing
Connection to localhost closed.

redmine@seraphim:~$ sudo -u git -i whoami
git
redmine@seraphim:~$ ssh -i iomega_prod/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa.pub git@localhost
Enter passphrase for key 'iomega_prod/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa.pub':
```
to create cert i used
```
redmine@seraphim:~$ ssh-keygen -N '' -f 'iomega_prod/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa'
```
so everything should work fine without -i and using that same key in in .ssh (renamed to is_rsa*) work fine.

**Comment by grawerpl** [comment]
ok, i found out problem.

actually passenger create sandbox when working as nginx extension so environment variable is't sent do passenger. 
to repeir this problem you must add to your server section
```
passenger_env_var PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;
```
thanks to that now plugin can find all command that needed to work properly.

**Comment by derats** [comment]
Good news!

**Comment by n-rodriguez** [comment]
> ok, i found out problem.

Doc updated : http://redmine-git-hosting.io/configuration/notes/

Thanks!
