### ISSUE TITLE
Cant plugins:migrate on clean redmine 3.2.0 install

### ISSUE THREAD

**Issue by HighwayStar** [jbox-web/redmine_git_hosting#563]
I'm trying to install plugin on clean redmine 3.2.0 and got following on redmine:plugins:migrate

```
== 20140618231512 CreateUniqueIndexes: migrating ==============================
-- add_index(:repository_git_extras, :repository_id, {:unique=>true})
   -> 0.0007s
-- add_index(:repository_git_notifications, :repository_id, {:unique=>true})
   -> 0.0005s
-- add_index(:repository_git_config_keys, :repository_id)
   -> 0.0005s
-- add_index(:repository_git_config_keys, [:key, :repository_id], {:unique=>true})
   -> 0.0007s
-- add_index(:repository_post_receive_urls, :repository_id)
   -> 0.0004s
-- add_index(:repository_post_receive_urls, [:url, :repository_id], {:unique=>true})
   -> 0.0007s
-- add_index(:repository_mirrors, :repository_id)
   -> 0.0004s
-- add_index(:repository_mirrors, [:url, :repository_id], {:unique=>true})
   -> 0.0007s
-- add_index(:repository_deployment_credentials, [:repository_id, :gitolite_public_key_id], {:unique=>true, :name=>"index_deployment_credentials_on_repository_id_and_public_key_id"})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_deployment_credentials_on_repository_id_and_public_key_id' on table 'repository_deployment_credentials' is too long; the limit is 62 characters/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:936:in `add_index_options'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:556:in `add_index'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:665:in `block in method_missing'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `block in say_with_time'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `say_with_time'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:654:in `method_missing'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:416:in `method_missing'
/local/tomin/devel/redmine-clean/plugins/redmine_git_hosting/db/migrate/20140618231512_create_unique_indexes.rb:17:in `up'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:571:in `up'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in `exec_migration'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in `block in migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in `migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in `migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `ddl_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in `block in migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `each'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:481:in `migrate_plugin'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:453:in `migrate'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:467:in `block in migrate'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:466:in `each'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:466:in `migrate'
/local/tomin/devel/redmine-clean/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
ArgumentError: Index name 'index_deployment_credentials_on_repository_id_and_public_key_id' on table 'repository_deployment_credentials' is too long; the limit is 62 characters
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:936:in `add_index_options'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:556:in `add_index'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:665:in `block in method_missing'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `block in say_with_time'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `say_with_time'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:654:in `method_missing'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:416:in `method_missing'
/local/tomin/devel/redmine-clean/plugins/redmine_git_hosting/db/migrate/20140618231512_create_unique_indexes.rb:17:in `up'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:571:in `up'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in `exec_migration'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in `block in migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in `migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in `migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `ddl_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in `block in migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `each'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/local/tomin/devel/redmine-clean/bundler/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:481:in `migrate_plugin'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:453:in `migrate'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:467:in `block in migrate'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:466:in `each'
/local/tomin/devel/redmine-clean/lib/redmine/plugin.rb:466:in `migrate'
/local/tomin/devel/redmine-clean/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

```

**Comment by n-rodriguez** [comment]
Fixed in commit : https://github.com/jbox-web/redmine_git_hosting/commit/1dacb343a4d2095893018d71a4fa419fc766bfc5
