### ISSUE TITLE
Redmine repository display issues

### ISSUE THREAD

**Issue by nina514** [jbox-web/redmine_git_hosting#603]
It pushed one time a large number of files.
An error occurred.

--------------------------- error message -------------------------
```
Started GET "/redmine/projects/project/repository" for 192.168.0.21 at 2016-05-13 18:20:10 +0900
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"project"}
  Current user: nina514 (id=5)
  Rendered repositories/_navigation.html.erb (61.6ms)
  Rendered repositories/_breadcrumbs.html.erb (0.3ms)
  Rendered repositories/_dir_list_content.html.erb (10.0ms)
  Rendered repositories/_dir_list.html.erb (10.1ms)
  Rendered repositories/_revision_graph.html.erb (0.5ms)
  Rendered repositories/_revisions.html.erb (7.5ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/show.html.erb within layouts/base (114.8ms)
Completed 500 Internal Server Error in 157ms (ActiveRecord: 46.2ms)

ActionView::Template::Error (Traceback (most recent call last):
  File "/usr/local/rvm/gems/ruby-2.0.0-p648/gems/github-markup-1.4.0/lib/github/commands/rest2html", line 47, in <module>
    from docutils import nodes
ImportError: No module named docutils):
    47:                        :id => @project, :page => nil, :key => User.current.rss_key})) %>
    48:    <% end %>
    49:
    50:    <%= call_hook(:view_repositories_show_bottom) %>
    51:
    52:    <% other_formats_links do |f| %>
    53:     <%= f.link_to 'Atom',
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/controllers/repositories_controller.rb:125:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by sdinot** [comment]
I had the same error. I resolved the issue by installing the "docutils" Python package on my system. This set of tools is used by the [github-markup](https://github.com/github/markup) library to process the RST files.
