### ISSUE TITLE
LoadError: cannot load such file -- github/markup

### ISSUE THREAD

**Issue by laoshaw** [jbox-web/redmine_git_hosting#604]
Invalid report. Sorry.

**Comment by laoshaw** [comment]
Now on ubuntu 1604 I "fixed" the github-markup by doing:

```bash
sudo apt-get install ruby-github-markup
```
Then I still could not proceed:
```bash
$ sudo bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant RedmineGitHosting::Haml
/usr/share/redmine/lib/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:33:in `<module:RedmineGitHosting>'
/usr/share/redmine/lib/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:29:in `<top (required)>'
/usr/share/redmine/lib/plugins/redmine_git_hosting/init.rb:5:in `block in <top (required)>'
/usr/share/redmine/config/initializers/00-core_plugins.rb:12:in `eval'
/usr/share/redmine/config/initializers/00-core_plugins.rb:12:in `block in <top (required)>'
/usr/share/redmine/config/initializers/00-core_plugins.rb:2:in `each'
/usr/share/redmine/config/initializers/00-core_plugins.rb:2:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:652:in `block in load_config_initializer'
/usr/lib/ruby/vendor_ruby/active_support/notifications.rb:166:in `instrument'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:651:in `load_config_initializer'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:615:in `each'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:615:in `block in <class:Engine>'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rails/application.rb:328:in `require_environment!'
/usr/lib/ruby/vendor_ruby/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `each'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.3.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```
