### ISSUE TITLE
ActionView::Template::Error (undefined method `accessor'...)

### ISSUE THREAD

**Issue by mcondarelli** [jbox-web/redmine_git_hosting#629]
I have a brand new installation as follows:
```
Information

Redmine 3.3.1.stable
Default administrator account changed 	
Attachments directory writable 	
Plugin assets directory writable (./public/plugin_assets) 	
RMagick available (optional) 	
ImageMagick convert available (optional) 	

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.10.2
  Filesystem                     
  Xitolite                       2.10.2
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.1
```
I ported the database from an older (TurnkeyLinux-based) installation and created a few projects and associated Gitolite repositories before noticing the problem.

Creating new issues or accessing older ones bombs with:
```
Started GET "/issues/4" for 127.0.0.1 at 2016-11-15 14:08:40 +0100
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"4"}
  Current user: mcon (id=3)
  Rendered issues/_action_menu.html.erb (15.3ms)
  Rendered issue_relations/_form.html.erb (3.2ms)
  Rendered issues/_relations.html.erb (35.6ms)
  Rendered issues/_history.html.erb (15.6ms)
  Rendered issues/_action_menu.html.erb (3.8ms)
  Rendered issues/_attributes.html.erb (9.1ms)
  Rendered issues/_form.html.erb (26.3ms)
  Rendered issues/_edit.html.erb (29.9ms)
  Rendered issues/show.html.erb within layouts/base (174.2ms)
Completed 500 Internal Server Error in 722ms (ActiveRecord: 469.5ms)

ActionView::Template::Error (undefined method `accessor' for #<ActiveRecord::Type::Value:0x000000043b2488>):
    15: <% end %>
    16:
    17: <% if @issue.safe_attribute? 'assigned_to_id' %>
    18: <p><%= f.select :assigned_to_id, principals_options_for_select(@issue.assignable_users, @issue.assigned_to), :include_blank => true, :required => @issue.required_attribute?('assigned_to_id') %></p>
    19: <% end %>
    20:
    21: <% if @issue.safe_attribute?('category_id') && @issue.project.issue_categories.any? %>
  app/models/role.rb:213:in `permissions_all_trackers'
  app/models/role.rb:222:in `permissions_all_trackers?'
  app/models/role.rb:228:in `permissions_tracker?'
  app/models/project.rb:532:in `block in assignable_users'
  app/models/project.rb:532:in `assignable_users'
  app/models/issue.rb:863:in `assignable_users'
  app/views/issues/_attributes.html.erb:18:in `block in _app_views_issues__attributes_html_erb__746098401345571946_89102060'
  app/helpers/application_helper.rb:1058:in `labelled_fields_for'
  app/views/issues/_attributes.html.erb:1:in `_app_views_issues__attributes_html_erb__746098401345571946_89102060'
  app/views/issues/_form.html.erb:42:in `block in _app_views_issues__form_html_erb__2372106100887406891_89054820'
  app/helpers/application_helper.rb:1058:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb__2372106100887406891_89054820'
  app/views/issues/_edit.html.erb:8:in `block in _app_views_issues__edit_html_erb___2066311912814283393_41061120'
  app/helpers/application_helper.rb:1051:in `labelled_form_for'
  app/views/issues/_edit.html.erb:1:in `_app_views_issues__edit_html_erb___2066311912814283393_41061120'
  app/views/issues/show.html.erb:136:in `_app_views_issues_show_html_erb___3769807404617755934_64019180'
  app/controllers/issues_controller.rb:117:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:114:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

What did I do wrong?
Any help appreciated.

**Comment by mcondarelli** [comment]
After a zillion tests it turned out I had forgotten a "rake db:migrate RAILS_ENV="production"" after last update.
Shame on me :(
