### ISSUE TITLE
Installation error (NameError: uninitialized constant RedmineGitHosting::Haml)

### ISSUE THREAD

**Issue by stitrace** [jbox-web/redmine_git_hosting#631]
Help please, what is that mean?
```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting --trace
(in /var/lib/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant RedmineGitHosting::Haml
/var/lib/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:34:in `<module:RedmineGitHosting>'
/var/lib/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:30:in `<top (required)>'
/var/lib/redmine/plugins/redmine_git_hosting/init.rb:5:in `<top (required)>'
/var/lib/redmine/lib/redmine/plugin.rb:155:in `block in load'
/var/lib/redmine/lib/redmine/plugin.rb:146:in `each'
/var/lib/redmine/lib/redmine/plugin.rb:146:in `load'
/var/lib/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/lib64/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `each'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib64/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/usr/lib64/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/lib64/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/usr/lib64/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/lib64/ruby/2.2.0/tsort.rb:345:in `each'
/usr/lib64/ruby/2.2.0/tsort.rb:345:in `call'
/usr/lib64/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/lib64/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/usr/lib64/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
/var/lib/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:328:in `require'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:328:in `require_environment!'
/usr/local/lib64/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `each'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `invoke_prerequisites'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/usr/local/lib64/ruby/gems/2.2.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<main>'
/usr/local/bin/ruby_executable_hooks22:15:in `eval'
/usr/local/bin/ruby_executable_hooks22:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by n-rodriguez** [comment]
Hi! I think you forgot to install plugin's gems
