### ISSUE TITLE
Strange error in template

### ISSUE THREAD

**Issue by fizista** [jbox-web/redmine_git_hosting#637]
If from the file "redmine_git_hosting / app / views / repositories / show.html.erb" I will remove the line:
`
    <% = Call_hook (: view_repositories_show_bottom)%>
`
it all works correctly.

```
tarted GET "/projects/pro_slubii/repository" for xx.xx.xx.xx at 2016-12-11 16:13:48 +0100
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"pro_slubii"}
  Current user: admin (id=1)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.haml (60.5ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_download_revision.html.haml (18.4ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_show_top.html.haml (96.2ms)
  Rendered repositories/_navigation.html.erb (56.0ms)
  Rendered repositories/_breadcrumbs.html.erb (8.6ms)
  Rendered repositories/_dir_list_content.html.erb (194.8ms)
  Rendered repositories/_dir_list.html.erb (204.0ms)
  Rendered repositories/_revision_graph.html.erb (12.5ms)
  Rendered repositories/_revisions.html.erb (329.2ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/show.html.erb within layouts/base (820.6ms)
Completed 500 Internal Server Error in 1146ms (ActiveRecord: 87.6ms)

ActionView::Template::Error (undefined method `split' for nil:NilClass):
    47:                        :id => @project, :page => nil, :key => User.current.rss_key})) %>
    48:    <% end %>
    49:
    50:    <%= call_hook(:view_repositories_show_bottom) %>
    51:
    52:    <% other_formats_links do |f| %>
    53:     <%= f.link_to 'Atom',
  lib/redmine/codeset_util.rb:48:in `to_utf8_by_setting_internal'
  lib/redmine/codeset_util.rb:39:in `to_utf8_by_setting'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/hooks/display_repository_readme.rb:59:in `get_formatter'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/hooks/display_repository_readme.rb:19:in `view_repositories_show_bottom'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  plugins/redmine_git_hosting/app/views/repositories/show.html.erb:50:in `_plugins_redmine_git_hosting_app_views_repositories_show_html_erb___1210543806300457773_70276859001800'
  app/controllers/repositories_controller.rb:125:in `show'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:40:in `show_with_git_hosting'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by n-rodriguez** [comment]
Hi! Is the repo well initialized? I already have this bug with an empty repo, with no branches at all (or no master branch, can't remember exactly ^^)

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
