### ISSUE TITLE
Error 500 on admin pages for 1.2.2

### ISSUE THREAD

**Issue by DProvorse** [jbox-web/redmine_git_hosting#643]
Performed an in place upgrade on plugin from 1.2.1 to 1.2.2 with git checkout. Redmine version 3.0.3 Ruby 2.2.3 and Rails 4.2.7.1

After the install, migrate and restart any attempt to hit the admin page generates an error 500 and the following in the production log.

Rolled back to 1.2.1 and everything is fine. Tried to run a rake task to reset defaults and reinstall update all hooks but neither resolved the issue.
```
`Started GET "/settings/plugin/redmine_git_hosting" for 70.189.195.184 at 2017-01-09 18:03:25 -0800
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_git_hosting"}
  Current user: dprovorse (id=3)
  Rendered plugins/redmine_bootstrap_kit/app/views/common/_modal_base.html.haml (2.3ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_hosting_js_headers.html.haml (14.4ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_ssh.html.haml (6.2ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_storage.html.haml (5.0ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_file.html.haml (8.3ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_global.html.haml (7.6ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_access.html.haml (20.9ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_hooks.html.haml (11.5ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_cache.html.haml (9.8ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_notify.html.haml (7.0ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_display_access.html.haml (7.5ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_redmine_config.html.haml (20.1ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_sidekiq_interface.html.haml (2.5ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_test.html.haml (818.2ms)
  Rendered common/_tabs.html.erb (977.5ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.haml (1009.0ms)
  Rendered settings/plugin.html.erb within layouts/admin (1035.0ms)
Completed 500 Internal Server Error in 1201ms (ActiveRecord: 16.7ms)

ActionView::Template::Error (no implicit conversion of nil into String):
    44:       - else
    45:         = image_tag('exclamation.png')
    46:
    47:   - gitolite_checks = RedmineGitHosting::Config.check_hooks_install!
    48:
    49:   %tr
    50:     %td= l(:label_gitolite_hooks_installed)
  plugins/redmine_git_hosting/lib/redmine_git_hosting/config/gitolite_hooks.rb:38:in `join'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/config/gitolite_hooks.rb:38:in `gitolite_hooks_dir'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_hook.rb:123:in `gitolite_hooks_dir'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_hook.rb:35:in `destination_path'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_hook.rb:107:in `file_exists?'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_hook.rb:52:in `installed?'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_hooks.rb:25:in `block in hooks_installed?'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_hooks.rb:24:in `each'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_hooks.rb:24:in `hooks_installed?'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/config/gitolite_hooks.rb:47:in `check_hooks_install!'
  plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_test.html.haml:47:in `_25c7fb6bbc7043fc15c9a712ca791022'
  app/views/common/_tabs.html.erb:17:in `block in _778f534a28a1f7eafac8ae0b31f1ee17'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_778f534a28a1f7eafac8ae0b31f1ee17'
  app/helpers/application_helper.rb:325:in `render_tabs'
  plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.haml:16:in `_d9b4c60a3ae5789e290e6e38b230ab35'
  app/views/settings/plugin.html.erb:6:in `block in _07935880747eb61344823b31b783f2b6'
  app/views/settings/plugin.html.erb:4:in `_07935880747eb61344823b31b783f2b6'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

```

**Comment by perltwiesekt** [comment]
I've same issue, could you please provide your solution in case you solved it?

**Comment by OgreTransporter** [comment]
I've same issue, could you please provide your solution in case you solved it?

**Comment by baby-gnu** [comment]
Which version of gitolite are you using ?

**Comment by baby-gnu** [comment]
Did you enabled the [LOCAL_CODE](http://gitolite.com/gitolite/non-core.html#localcode) setting in `.gitolite.rc`?

Regards.

**Comment by perltwiesekt** [comment]
Enabled the setting in `.gitolite.rc` and now it works, thanks!
