### ISSUE TITLE
undefined method `watcher_link' - 500 error

### ISSUE THREAD

**Issue by sacerro** [jbox-web/redmine_git_hosting#656]
Hi, 
I upgrade redmine and redmine git hosting plugin.- All settings are ok and ssh keys too. Repos are working in ssh session but when I try to see in web, it's return 500 error. It's this a plugin error or something related with my redmine installation? Help me, please!

Error trace:
Showing /home/redmine/plugins/redmine_git_hosting/app/views/repositories/_navigation.html.erb where line 5 raised:

undefined method `watcher_link' for #<#<Class:0x007f4320eea3a8>:0x007f432119ac88>

Trace of template inclusion: plugins/redmine_git_hosting/app/views/repositories/show.html.erb

Rails.root: /home/redmine

```
plugins/redmine_git_hosting/app/views/repositories/_navigation.html.erb:5:in `_plugins_redmine_git_hosting_app_views_repositories__navigation_html_erb__3771883399564110937_69963155498060'
actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.7.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.7.1) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.7.1) lib/action_view/template.rb:143:in `render'
actionview (4.2.7.1) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
actionview (4.2.7.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.7.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:51:in `render_partial'
actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:25:in `render'
actionview (4.2.7.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
plugins/redmine_git_hosting/app/views/repositories/show.html.erb:4:in `_plugins_redmine_git_hosting_app_views_repositories_show_html_erb__961822230812308148_69963146093220'
actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.7.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.7.1) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.7.1) lib/action_view/template.rb:143:in `render'
actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:46:in `render_template'
actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:27:in `render'
actionview (4.2.7.1) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.7.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.7.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.7.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.7.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
wicked_pdf (1.1.0) lib/wicked_pdf/pdf_helper.rb:42:in `render_with_wicked_pdf'
app/controllers/repositories_controller.rb:125:in `show'
plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:40:in `show_with_git_hosting'
actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:313:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:312:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:312:in `block in halting'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:497:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
rack (1.6.5) lib/rack/etag.rb:24:in `call'
rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.5) lib/rack/head.rb:13:in `call'
actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.5) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.5) lib/rack/content_length.rb:15:in `call'
rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
railties (4.2.7.1) lib/rails/application.rb:165:in `call'
railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

This is my redmine installation

```
Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Mercurial                      1.4
  Git                            1.7.1
  Filesystem                     
  Xitolite                       1.7.1
Redmine plugins:
  advanced_roadmap               0.10.1
  easy_gantt                     1.7
  ff_create_issue                0.0.1
  mega_calendar                  1.6.0
  redmine_agile                  1.4.2
  redmine_bootstrap_kit          0.2-devel
  redmine_checklists             3.1.5
  redmine_ckeditor               1.1.4
  redmine_contacts               4.0.6
  redmine_contacts_invoices      4.1.4
  redmine_dashboard              3.0.0.dev0
  redmine_finance                2.1.1
  redmine_git_hosting            1.2.2
  redmine_glanceyear             0.0.1
  redmine_helpdesk               0.0.15
  redmine_issue_badge            0.0.3
  redmine_lightbox2              0.3.2
  redmine_mylyn_connector        2.8.2.stable
  redmine_open_links_in_new_window 0.0.3
  redmine_people                 1.1.1
  redmine_silencer               0.4.1
  redmine_webhook                0.0.2

```

**Comment by n-rodriguez** [comment]
Hi! You're on the wrong git branch.

```git checkout 1.2.2```
