### ISSUE TITLE
Cannot delete repositories

### ISSUE THREAD

**Issue by y-spreen** [jbox-web/redmine_git_hosting#667]
This seems to be issue [#586](https://github.com/jbox-web/redmine_git_hosting/issues/586), but I could not find a fix.

From `production.log`:
```
Started DELETE "/repositories/104" for ${IP} at 2017-04-11 16:29:18 +0200
Processing by RepositoriesController#destroy as HTML
  Parameters: {"authenticity_token"=>"${token}", "id"=>"104"}
  Current user: ${user} (id=5)
Completed 500 Internal Server Error in 352ms (ActiveRecord: 327.5ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'redmine.repository_git_notifications' doesn't exist: SHOW FULL FIELDS FROM `repository_git_notifications`):
  app/controllers/repositories_controller.rb:109:in `destroy'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:58:in `destroy_with_git_hosting'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by gituser** [comment]
Try creating `repository_git_notifications` table:

```
CREATE TABLE `repository_git_notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `repository_id` int(11) DEFAULT NULL,
  `include_list` text,
  `exclude_list` text,
  `prefix` varchar(255) DEFAULT NULL,
  `sender_address` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_repository_git_notifications_on_repository_id` (`repository_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by nO-OnE-910** [comment]
Shouldn't this be handled by the migration of the plugin? That went through without issues btw.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
