### ISSUE TITLE
cannot load such file -- github/markup (LoadError)

### ISSUE THREAD

**Issue by MarcusWichelmann** [jbox-web/redmine_git_hosting#672]
I'm trying to install this plugin and followed the instructions at http://redmine-git-hosting.io/get_started/ but get stuck at running `bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting` with the following output:
```
root@MARCUS-VSERVER:/usr/share/redmine# bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
rake aborted!
LoadError: cannot load such file -- github/markup
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/usr/share/redmine/lib/plugins/redmine_git_hosting/lib/redmine_git_hosting/hooks/display_repository_readme.rb:1:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/usr/share/redmine/lib/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:24:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/usr/share/redmine/lib/plugins/redmine_git_hosting/init.rb:5:in `block in <top (required)>'
/usr/share/redmine/config/initializers/00-core_plugins.rb:12:in `eval'
/usr/share/redmine/config/initializers/00-core_plugins.rb:12:in `block in <top (required)>'
/usr/share/redmine/config/initializers/00-core_plugins.rb:2:in `each'
/usr/share/redmine/config/initializers/00-core_plugins.rb:2:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:241:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/engine.rb:648:in `block in load_config_initializer'
/var/lib/gems/2.1.0/gems/activesupport-4.1.16/lib/active_support/notifications.rb:161:in `instrument'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/engine.rb:647:in `load_config_initializer'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/engine.rb:611:in `each'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/engine.rb:611:in `block in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/application.rb:300:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/application.rb:276:in `require'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/application.rb:276:in `require_environment!'
/var/lib/gems/2.1.0/gems/railties-4.1.16/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/var/lib/gems/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

The output of `bundle install --without development test` has been this:
```
root@MARCUS-VSERVER:/usr/share/redmine# bundle install --without development test
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on
this machine.
Using rake 12.0.0
Using i18n 0.8.1
Using json 1.8.6
Using minitest 5.10.1
Using thread_safe 0.3.6
Using tzinfo 1.2.3
Using activesupport 4.1.16
Using builder 3.2.3
Using erubis 2.7.0
Using actionview 4.1.16
Using rack 1.5.5
Using rack-test 0.6.3
Using actionpack 4.1.16
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mail 2.6.5
Using actionmailer 4.1.16
Using actionpack-action_caching 1.2.0
Using activemodel 4.1.16
Using arel 5.0.1.20140414130214
Using activerecord 4.1.16
Using awesome_nested_set 3.1.2
Using coderay 1.1.1
Using concurrent-ruby 1.0.5
Using thor 0.19.4
Using railties 4.1.16
Using jquery-rails 3.1.4
Using mysql2 0.3.21
Using net-ldap 0.16.0
Using protected_attributes 1.1.3
Using ruby-openid 2.7.0
Using rack-openid 1.4.2
Using bundler 1.7.4
Using sprockets 3.7.1
Using sprockets-rails 2.3.3
Using rails 4.1.16
Using redcarpet 3.4.0
Using request_store 1.3.2
Using rmagick 2.16.0
Your bundle is complete!
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

I already tried to install github-markup manually:
```
root@MARCUS-VSERVER:/usr/share/redmine# gem install github-markup
Successfully installed github-markup-1.6.0
Parsing documentation for github-markup-1.6.0
Done installing documentation for github-markup after 0 seconds
1 gem installed
```

And run an update:
```
root@MARCUS-VSERVER:/usr/share/redmine# bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 12.0.0
Using i18n 0.8.1
Using json 1.8.6
Using minitest 5.10.1
Using thread_safe 0.3.6
Using tzinfo 1.2.3
Using activesupport 4.1.16
Using builder 3.2.3
Using erubis 2.7.0
Using actionview 4.1.16
Using rack 1.5.5
Using rack-test 0.6.3
Using actionpack 4.1.16
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mail 2.6.5
Using actionmailer 4.1.16
Using actionpack-action_caching 1.2.0
Using activemodel 4.1.16
Using arel 5.0.1.20140414130214
Using activerecord 4.1.16
Using awesome_nested_set 3.1.2
Using bundler 1.7.4
Using coderay 1.1.1
Using concurrent-ruby 1.0.5
Using thor 0.19.4
Using railties 4.1.16
Using jquery-rails 3.1.4
Using mysql2 0.3.21
Using net-ldap 0.16.0
Using protected_attributes 1.1.3
Using ruby-openid 2.7.0
Using rack-openid 1.4.2
Using sprockets 3.7.1
Using sprockets-rails 2.3.3
Using rails 4.1.16
Using redcarpet 3.4.0
Using request_store 1.3.2
Using rmagick 2.16.0
Your bundle is updated!
Gems in the groups development and test were not installed.
```

But none of it changed anything.

My Gemfile looks like this:
```
# Gitolite Admin repository management
gem 'gitolite-rugged', git: 'https://github.com/jbox-web/gitolite-rugged.git', tag: '1.2.0'

## Redmine 3.x
## Ruby/Rack Git Smart-HTTP Server Handler (use our own repository because Redmine uses Rails 4.2 and Rack 1.6)
#gem 'gitlab-grack', git: 'https://github.com/jbox-web/grack.git', require: 'grack', branch: 'fix_rails4'
#gem 'redcarpet', '~> 3.3.2'

## Redmine 2.x
## Ruby/Rack Git Smart-HTTP Server Handler (use our own repository because Redmine still uses Rails 3 and Rack 1.4)
gem 'gitlab-grack', git: 'https://github.com/jbox-web/grack.git', require: 'grack', branch: 'fix_rails3'
gem 'redcarpet', '~> 3.3.2'

# HAML views
gem 'haml-rails'

# Memcached client for GitCache
gem 'dalli'

# Redis client for GitCache
gem 'redis'
gem 'hiredis'

# Syntaxic coloration
gem 'github-markup'
gem 'RedCloth'
gem 'org-ruby'
gem 'creole'
# gem 'wikicloth'
gem 'asciidoctor'

# Rack parser for Hrack
gem 'rack-parser', require: 'rack/parser'
```

Im running Debian 8 (Jessie) and installed redmine (something like 2.5.x) and all it's dependencies from the repositories.
Also I am quiet new to ruby and it's package management sytem and therefor don't really know how to debug this further.

Do you have any ideas how to solve this issue that currently stops the whole Redmine-Instance from running because of exactly the same error message? Any help would be much appreciated! :D

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
