### ISSUE TITLE
plugins/redmine_git_hosting/app/views/repositories/_download_revision.html.haml : broken on FreeBSD

### ISSUE THREAD

**Issue by craig001** [jbox-web/redmine_git_hosting#693]
not sure if it is my setup but plugins/redmine_git_hosting/app/views/repositories/_download_revision.html.haml is causing 500 errors and logs are showing;

```
Started GET "/projects/oka/repository" for 192.168.1.136 at 2017-08-24 18:21:28 +0000
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"oka"}
  Current user: craig (id=5)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.haml (15.3ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_download_revision.html.haml (2.9ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_show_top.html.haml (19.3ms)
  Rendered repositories/_navigation.html.erb (107.8ms)
  Rendered repositories/_breadcrumbs.html.erb (1.4ms)
  Rendered repositories/_dir_list_content.html.erb (61.0ms)
  Rendered repositories/_dir_list.html.erb (62.3ms)
  Rendered repositories/_revision_graph.html.erb (4.3ms)
  Rendered repositories/_revisions.html.erb (101.0ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.haml (6.8ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_download_revision.html.haml (192.5ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_sidebar.html.erb (202.6ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/show.html.erb within layouts/base (648.9ms)
Completed 500 Internal Server Error in 976ms (ActiveRecord: 344.4ms)

ActionView::Template::Error (undefined local variable or method `repository' for #<#<Class:0x00000813613760>:0x0000081954a288>):
    1: - if repository.downloadable?
    2:   - content_for :header_tags do
    3:     = bootstrap_load_module(:font_awesome)
    4: 
  plugins/redmine_git_hosting/app/views/repositories/_download_revision.html.haml:1:in `_plugins_redmine_git_hosting_app_views_repositories__download_revision_html_haml___1390090918921536431_17416122240'
  plugins/redmine_git_hosting/app/views/repositories/_sidebar.html.erb:22:in `_plugins_redmine_git_hosting_app_views_repositories__sidebar_html_erb__2842534914489906047_17416689720'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  plugins/redmine_git_hosting/app/views/repositories/show.html.erb:76:in `block in _plugins_redmine_git_hosting_app_views_repositories_show_html_erb___663533681366913430_17342339020'
  plugins/redmine_git_hosting/app/views/repositories/show.html.erb:61:in `_plugins_redmine_git_hosting_app_views_repositories_show_html_erb___663533681366913430_17342339020'
  app/controllers/repositories_controller.rb:97:in `show'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:40:in `show_with_git_hosting'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
If I empty that file the repository renders correctly.

**Comment by craig001** [comment]
FreeBSD 11.1 amd64,
redmine 3.4.2
redmine_bootstrap_kit 0.2.5
redmine_git_hosting 1.2.3

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
