### ISSUE TITLE
bundle exec rake redmine_git_hosting:prepare_migration_to_v1 RAILS_ENV=production not working

### ISSUE THREAD

**Issue by yboiziau** [jbox-web/redmine_git_hosting#705]
Hello,

I have the following :

Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.10.4
  Filesystem                     
Redmine plugins:
  redmine_git_hosting            0.7.10

I've done the upgrade to 0.7.10 successfully but when I want to prepare migration to v1.2.3 via bundle exec rake redmine_git_hosting:prepare_migration_to_v1 RAILS_ENV=production I get the following error :

Delete SSH keys in Gitolite (they will be recreated later)

  - Delete SSH key redmine_someguy@redmine_1422627916_894831
rake aborted!
NoMethodError: undefined method `ssh_keys' for nil:NilClass
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users_helper.rb:49:in `remove_inactive_key'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users_helper.rb:12:in `handle_ssh_key_delete'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users.rb:45:in `block in delete_ssh_keys'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:179:in `block in wrapped_transaction'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:164:in `block in get_lock'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:159:in `open'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:159:in `get_lock'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin.rb:176:in `wrapped_transaction'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users.rb:44:in `delete_ssh_keys'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/admin_users.rb:22:in `delete_ssh_key'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/shell.rb:66:in `handle_command'
/home/redmine/plugins/redmine_git_hosting/lib/redmine_gitolite/git_hosting.rb:44:in `resync_gitolite'
/home/redmine/plugins/redmine_git_hosting/lib/tasks/migration_tools.rake:18:in `block (4 levels) in <top (required)>'
/home/redmine/plugins/redmine_git_hosting/lib/tasks/migration_tools.rake:10:in `each'
/home/redmine/plugins/redmine_git_hosting/lib/tasks/migration_tools.rake:10:in `block (3 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/redmine/plugins/redmine_git_hosting/lib/tasks/migration_tools.rake:29:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine_git_hosting:migration_tools:delete_ssh_key

Here are  the gems that are currently installed :

actionmailer (3.2.21, 3.2.17)
actionpack (3.2.21, 3.2.17)
activemodel (3.2.21, 3.2.17)
activerecord (3.2.21, 3.2.17)
activeresource (3.2.21, 3.2.17)
activesupport (3.2.21, 3.2.17)
acts-as-taggable-on (2.3.3)
arel (3.0.3)
asciidoctor (1.5.2)
awesome_nested_set (2.1.6)
builder (3.0.4, 3.0.0)
bundler (1.16.1)
capybara (2.4.4)
celluloid (0.16.0)
charlock_holmes (0.7.3)
climate_control (0.0.3)
cliver (0.3.2)
cocaine (0.5.5)
coderay (1.1.0)
creole (0.5.0)
dalli (2.7.2)
database_cleaner (1.4.0)
dav4rack (0.3.0)
diff-lcs (1.2.5)
docile (1.1.5)
erubis (2.7.0)
faraday (0.8.9)
faraday_middleware (0.9.1)
ffi (1.9.6)
formatador (0.2.5)
fuubar (1.3.3)
github-markup (1.3.1)
gitlab-grit (2.7.3)
gratr19 (0.4.4.1)
guard (2.11.1)
guard-compat (1.2.1)
guard-rspec (4.5.0)
haml (4.0.6)
haml-rails (0.4)
hashie (1.2.0)
hike (1.2.3)
hiredis (0.5.2)
hitimes (1.2.2)
htmlentities (4.3.3)
i18n (0.7.0, 0.6.11)
inifile (3.0.0)
jbox-gitolite (1.2.6)
journey (1.0.4)
jquery-rails (3.1.2, 2.0.3)
json (1.8.2)
kaminari (0.16.2)
listen (2.8.5)
lockfile (2.1.3)
lumberjack (1.0.9)
mail (2.5.4)
method_source (0.8.2)
mime-types (1.25.1)
mini_portile (0.6.2)
money (5.1.1)
multi_json (1.10.1)
multipart-post (1.2.0)
mysql2 (0.3.17)
nenv (0.2.0)
net-ldap (0.3.1)
nokogiri (1.6.6.2)
notiffany (0.0.3)
org-ruby (0.9.12)
paperclip (3.5.4)
poltergeist (1.5.1)
polyglot (0.3.5)
posix-spawn (0.3.9)
power_assert (0.2.2)
pry (0.10.1)
rack (1.4.5)
rack-cache (1.2)
rack-openid (1.4.2)
rack-raw-upload (1.1.1)
rack-ssl (1.3.4)
rack-test (0.6.3)
rails (3.2.21, 3.2.17)
railties (3.2.21, 3.2.17)
rake (10.4.2, 10.1.1)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rbpdf (1.18.5)
rdoc (3.12.2)
redcarpet (2.3.0)
RedCloth (4.2.9)
redis (3.2.0)
redmine_acts_as_taggable_on (1.0.0)
request_store (1.0.5)
rich (1.4.6)
rmagick (2.13.4)
rspec (2.99.0)
rspec-collection_matchers (1.1.2)
rspec-core (2.99.2)
rspec-expectations (2.99.2)
rspec-mocks (2.99.3)
rspec-rails (2.99.0)
ruby-ole (1.2.11.8)
ruby-openid (2.3.0)
ruby-progressbar (1.7.1)
rubypants (0.2.0)
rubyzip (1.1.6)
rugged (0.21.4)
sass (3.4.10)
sass-rails (3.2.6)
shellany (0.0.1)
simple_enum (1.6.9)
simplecov (0.9.1)
simplecov-html (0.8.0)
simplecov-rcov (0.2.3)
slop (3.6.0)
spreadsheet (0.6.9)
sprockets (2.2.3)
test-unit (3.0.9)
thor (0.19.1)
tilt (1.4.1)
timers (4.0.1)
transifex-ruby-fork-jg (0.1.0)
treetop (1.4.15)
tzinfo (0.3.42)
uuidtools (2.1.5)
vcard (0.2.12)
websocket-driver (0.5.1)
websocket-extensions (0.1.1)
xapian-full-alaveteli (1.2.9.5)
xpath (2.0.0)
ya2yaml (0.31)
zip-zip (0.3)

I'm running Debian 7 (Linux gitomine 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux)

What can I do ?

Thanks

**Comment by yboiziau** [comment]
I've resolved it on my own. I figured out that there were no symlinks between  /home/redmine/.ssh/redmine_gitolite_admin_id_rsa and /home/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa
due to the migration to 0.7.10
