### ISSUE TITLE
422 Error on repository creation

### ISSUE THREAD

**Issue by sacerro** [jbox-web/redmine_git_hosting#712]
Hi,

I installed following web instructions and gitolite seems to work fine. When I try to create a new Repository it returns 422 error and my project cannot be load (500 error).

Git_hosting_log:
```
2018-03-27 23:51:36 +0200 [INFO] Flush Git Cache !

2018-03-27 23:51:36 +0200 [INFO] Done !

2018-03-27 23:51:49 +0200 [INFO] Flush Settings Cache !

2018-03-27 23:51:49 +0200 [INFO] Settings cache flushed!

2018-03-27 23:51:49 +0200 [INFO] Forced resync of all ssh keys...

2018-03-27 23:51:50 +0200 [INFO] resync_ssh_keys : SSH key 'redmine_admin_1@redmine_Home' already exists in Gitolite, update it ...

2018-03-27 23:51:50 +0200 [INFO] resync_ssh_keys : commiting to Gitolite...

2018-03-27 23:51:51 +0200 [INFO] Flush Git Cache !

2018-03-27 23:51:51 +0200 [INFO] Enable RW access on all Gitolite repositories

2018-03-27 23:51:52 +0200 [INFO] enable_rw_access : '@all' repository already configured, check for RedmineGitHosting key presence

2018-03-27 23:51:52 +0200 [INFO] enable_rw_access : RedmineGitHosting key is present, nothing to do.

2018-03-27 23:51:52 +0200 [INFO] enable_rw_access : commiting to Gitolite...

2018-03-27 23:51:53 +0200 [INFO] Testing if Redmine user 'MYUSER' can sudo to Gitolite user 'MYGITUSER'...

2018-03-27 23:51:53 +0200 [INFO] OK!
```

I try delete cache, and reconfigure plugin but nothing...  It seems to connect and have permission:

-bash-4.2$ ssh -i ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info
hello redmine_gitolite_admin_id_rsa, this is git@localhost running gitolite3 v3.6.7-19-g2cfc81f on git 1.8.3.1
R W    gitolite-admin

Can you help me please? I have no idea what's happening...

**Comment by sacerro** [comment]
In error log I had: 

ActiveRecord::RecordInvalid (Validation failed: Git http no está incluido en la lista):
  plugins/redmine_git_hosting/app/use_cases/repositories/create.rb:16:in `set_repository_extra'
  plugins/redmine_git_hosting/app/use_cases/repositories/create.rb:6:in `call'
  plugins/redmine_git_hosting/app/use_cases/repositories/base.rb:22:in `call'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:90:in `call_use_cases'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:47:in `create_with_git_hosting'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Hope this can help solve this issue

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
