### ISSUE TITLE
redmine_git_hosting plugin requires the additionals plugin

### ISSUE THREAD

**Issue by mrPsycho** [jbox-web/redmine_git_hosting#739]
Hello,

truing to install new fresh 4.0.0, and see this error: 
```
redmine@redmine:~/redmine$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting
rake aborted!
Redmine::PluginRequirementError: redmine_git_hosting plugin requires the additionals plugin
/home/redmine/redmine/lib/redmine/plugin.rb:275:in `rescue in requires_redmine_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:272:in `requires_redmine_plugin'
/home/redmine/redmine/plugins/redmine_git_hosting/init.rb:16:in `block in <top (required)>'
/home/redmine/redmine/lib/redmine/plugin.rb:92:in `instance_eval'
/home/redmine/redmine/lib/redmine/plugin.rb:92:in `register'
/home/redmine/redmine/plugins/redmine_git_hosting/init.rb:4:in `<top (required)>'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/redmine/lib/redmine/plugin.rb:175:in `block in load'
/home/redmine/redmine/lib/redmine/plugin.rb:166:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:166:in `load'
/home/redmine/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/redmine/.bundler/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

Caused by:
Redmine::PluginNotFound: Redmine::PluginNotFound
/home/redmine/redmine/lib/redmine/plugin.rb:143:in `find'
/home/redmine/redmine/lib/redmine/plugin.rb:273:in `requires_redmine_plugin'
/home/redmine/redmine/plugins/redmine_git_hosting/init.rb:16:in `block in <top (required)>'
/home/redmine/redmine/lib/redmine/plugin.rb:92:in `instance_eval'
/home/redmine/redmine/lib/redmine/plugin.rb:92:in `register'
/home/redmine/redmine/plugins/redmine_git_hosting/init.rb:4:in `<top (required)>'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/redmine/lib/redmine/plugin.rb:175:in `block in load'
/home/redmine/redmine/lib/redmine/plugin.rb:166:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:166:in `load'
/home/redmine/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.bundler/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/home/redmine/.bundler/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/redmine/.bundler/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

did all the things pointed there: http://redmine-git-hosting.io/get_started/

**Comment by mrPsycho** [comment]
https://github.com/alphanodes/additionals

`additionals` - is the name of plugin. ok.

**Comment by acosonic** [comment]
What @mrPsycho  means is that tutorial at:

[http://redmine-git-hosting.io/get_started/](http://redmine-git-hosting.io/get_started/)

is missing a step to install [http://redmine-git-hosting.io/get_started/](https://github.com/alphanodes/additionals)

**Comment by n-rodriguez** [comment]
> hat @mrPsycho means is that tutorial at:
> 
> http://redmine-git-hosting.io/get_started/
> 
> is missing a step to install [https://github.com/alphanodes/additionals/](https://github.com/alphanodes/additionals)

You're right. I will update the doc soon. Thanks!
