### ISSUE TITLE
500 on /repositories/<repo_number>/mirrors/new

### ISSUE THREAD

**Issue by pulecp** [jbox-web/redmine_git_hosting#753]
I use following environment with this plugin version https://github.com/jbox-web/redmine_git_hosting/archive/4.0.1.tar.gz.

```
Environment:
  Redmine version                4.0.6.stable
  Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
  Xitolite                       2.20.1
Redmine plugins:
  additionals                    2.0.22
  redmine_agile                  1.5.3
  redmine_checklists             3.1.16
  redmine_default_assign         0.6
  redmine_git_hosting            4.0.1
  redmine_ldap_sync              2.1.1.devel
  redmine_mentions               0.1.1
  redmine_sidekiq                2.1.0
  redmine_subtasks_inherited_fields 1.1.1
  redmineup_tags                 2.0.8
```

and i see this fatal error in logs when I try to create new mirror:

```console
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: F, [2020-04-07T12:02:55.685520 #35] FATAL -- :
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: F, [2020-04-07T12:02:55.685592 #35] FATAL -- : ActionView::Template::Error (undefined local variable or method `push_mode' for #<RepositoryMirror:0x000055c18d6ac558>
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: Did you mean?  push_mode_to_s):
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: F, [2020-04-07T12:02:55.685676 #35] FATAL -- :     12:
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]:    13:   p = f.check_box :active
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]:    14:   p = f.select :push_mode,
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]:    15:                options_for_select(mirrors_options, @mirror.push_mode_to_s),
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]:    16:                { label: :label_mirror_push_mode },
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]:    17:                onchange: "push_mode_change(this); return false;"
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]:    18:
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: F, [2020-04-07T12:02:55.685692 #35] FATAL -- :
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: F, [2020-04-07T12:02:55.685706 #35] FATAL -- : plugins/redmine_git_hosting/app/models/repository_mirror.rb:49:in `push_mode_to_s'
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: plugins/redmine_git_hosting/app/views/repository_mirrors/_form.html.slim:15:in `_21761e7433b6d1ba452d2a5a788f0ecd'
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: plugins/redmine_git_hosting/app/views/repository_mirrors/new.html.slim:5:in `block in _3841012038a52e43c373513ab26f3555'
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: app/helpers/application_helper.rb:1242:in `labelled_form_for'
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: plugins/redmine_git_hosting/app/views/repository_mirrors/new.html.slim:1:in `_3841012038a52e43c373513ab26f3555'
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: lib/redmine/sudo_mode.rb:63:in `sudo_mode'
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: 172.20.0.1 - - [07/Apr/2020:12:02:55 UTC] "GET /repositories/1039/mirrors/new HTTP/1.1" 500 648
Apr  7 14:02:55 redmine 7f29e82c72a8[1350]: https://redmine.example.com/repositories/1039/mirrors -> /repositories/1039/mirrors/new

**Comment by alexandermeindl** [comment]
Hi @pulecp 
this bug is fixed in release 5.0.0.
