### ISSUE TITLE
LoadError: cannot load such file -- github/markup

### ISSUE THREAD

**Issue by kepon85** [jbox-web/redmine_git_hosting#758]
Hello,

I installed Redmine via the Debian packages: https://wiki.debian.org/Redmine

> Environment:
>   Redmine version                4.0.7.stable
>   Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
>   Rails version                  5.2.2.1
>   Environment                    production
>   Database adapter               Mysql2
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> SCM:
>   Git                            2.20.1

But I can't install the redmine-git-hosting plugin

Dependance ok : 

```
# apt-get install build-essential libssh2-1 libssh2-1-dev cmake libgpg-error-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
uild-essential is already the newest version (12.6).
cmake is already the newest version (3.13.4-1).
libgpg-error-dev is already the newest version (1.35-1).
libssh2-1 is already the newest version (1.8.0-2.1).
libssh2-1-dev is already the newest version (1.8.0-2.1).
0 upgraded, 0 newly installed, 0 to remove and 61 not upgraded.
```

And if I follow the documentation:

```
root@mailgw:/usr/share/redmine/lib/plugins# git clone https://github.com/jbox-web/redmine_bootstrap_kit.git
Cloning into 'redmine_bootstrap_kit'...
remote: Enumerating objects: 751, done.
remote: Total 751 (delta 0), reused 0 (delta 0), pack-reused 751
Receiving objects: 100% (751/751), 2.29 MiB | 3.96 MiB/s, done.
Resolving deltas: 100% (249/249), done.
root@mailgw:/usr/share/redmine/lib/plugins# cd redmine_bootstrap_kit/
root@mailgw:/usr/share/redmine/lib/plugins/redmine_bootstrap_kit# git checkout 0.2.5
Note: checking out '0.2.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 791cdc9 Merge branch 'devel' into v0.2.x
root@mailgw:/usr/share/redmine/lib/plugins/redmine_bootstrap_kit# cd ..
root@mailgw:/usr/share/redmine/lib/plugins#  git clone https://github.com/jbox-web/redmine_git_hosting.git
Cloning into 'redmine_git_hosting'...
remote: Enumerating objects: 114, done.
remote: Counting objects: 100% (114/114), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 27053 (delta 38), reused 58 (delta 22), pack-reused 26939
Receiving objects: 100% (27053/27053), 7.54 MiB | 7.88 MiB/s, done.
Resolving deltas: 100% (16380/16380), done.
root@mailgw:/usr/share/redmine/lib/plugins#  cd redmine_git_hosting/
root@mailgw:/usr/share/redmine/lib/plugins/redmine_git_hosting# git checkout 4.0.0
Note: checking out '4.0.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e5d9a68d 4.0.0
root@mailgw:/usr/share/redmine/lib/plugins/redmine_git_hosting# cd ..
root@mailgw:/usr/share/redmine/lib/plugins# cd ..
root@mailgw:/usr/share/redmine/lib# 
root@mailgw:/usr/share/redmine/lib# cd ..
root@mailgw:/usr/share/redmine# bundle install --without development test
[DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'development test'`, and stop using this flag
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break
this application for all non-root users on this machine.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
Using rake 13.0.1
Using concurrent-ruby 1.1.6
Using i18n 1.6.0
Using minitest 5.14.1
Using thread_safe 0.3.6
Using tzinfo 1.2.7
Using activesupport 5.2.2.1
Using builder 3.2.4
Using erubi 1.9.0
Using nokogiri 1.10.0
Using rails-dom-testing 2.0.3
Using crass 1.0.2
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 5.2.2.1
Using rack 2.0.6
Using rack-test 0.7.0
Using actionpack 5.2.2.1
Using nio4r 2.3.1
Using websocket-extensions 0.1.2
Using websocket-driver 0.6.3
Using actioncable 5.2.2.1
Using globalid 0.3.6
Using activejob 5.2.2.1
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailer 5.2.2.1
Using method_source 0.9.2
Using thor 0.19.4
Using railties 5.2.2.1
Using actionpack-xml_parser 2.0.1
Using activemodel 5.2.2.1
Using arel 9.0.0
Using activerecord 5.2.2.1
Using mimemagic 0.3.2
Using marcel 0.3.2
Using activestorage 5.2.2.1
Using public_suffix 3.0.3
Using addressable 2.5.2
Using bundler 2.1.4
Using css_parser 1.6.0
Using csv 3.0.2
Using htmlentities 4.3.3
Using mysql2 0.5.2
Using net-ldap 0.16.1
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 5.2.2.1
Using rbpdf-font 1.19.1
Using rbpdf 1.19.5
Using redcarpet 3.4.0
Using request_store 1.3.0
Using rmagick 2.16.0
Using roadie 3.2.2
Using roadie-rails 1.3.0
Using rouge 3.19.0
Bundle complete! 19 Gemfile dependencies, 56 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
root@mailgw:/usr/share/redmine# bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting
 
rake aborted!
LoadError: cannot load such file -- github/markup
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/redmine/lib/plugins/redmine_git_hosting/lib/redmine_git_hosting/hooks.rb:1:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/redmine/lib/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:8:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/redmine/lib/plugins/redmine_git_hosting/init.rb:2:in `block in <top (required)>'
/usr/share/redmine/config/initializers/00-core_plugins.rb:12:in `eval'
/usr/share/redmine/config/initializers/00-core_plugins.rb:12:in `block in <top (required)>'
/usr/share/redmine/config/initializers/00-core_plugins.rb:2:in `each'
/usr/share/redmine/config/initializers/00-core_plugins.rb:2:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `block in load'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:170:in `instrument'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `each'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `each'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require_environment!'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

Thank's for your help

**Comment by alexandermeindl** [comment]
This should be fixed in release 5.0.0. If your problem exists with this version, feel free and reopen this issue.
