### ISSUE TITLE
NameError: uninitialized constant RSpec

### ISSUE THREAD

**Issue by n0rvik** [jbox-web/redmine_git_hosting#771]
<pre>
[redmine@rm2-test ~/redmine]$ bundle exec rake redmine:plugins
rake aborted!
NameError: uninitialized constant RSpec
/mnt/storage/opt/redmine/redmine/plugins/redmine_git_hosting/lib/tasks/ci_tools.rake:4:in `block (2 levels) in <top (required)>'
/mnt/storage/opt/redmine/redmine/plugins/redmine_git_hosting/lib/tasks/ci_tools.rake:2:in `block in <top (required)>'
/mnt/storage/opt/redmine/redmine/plugins/redmine_git_hosting/lib/tasks/ci_tools.rake:1:in `<top (required)>'
/mnt/storage/opt/redmine/redmine/lib/tasks/redmine.rake:202:in `load'
/mnt/storage/opt/redmine/redmine/lib/tasks/redmine.rake:202:in `block in <top (required)>'
/mnt/storage/opt/redmine/redmine/lib/tasks/redmine.rake:202:in `each'
/mnt/storage/opt/redmine/redmine/lib/tasks/redmine.rake:202:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:656:in `load'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:656:in `block in run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:656:in `each'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:656:in `run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/application.rb:515:in `run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:459:in `load_tasks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/railtie.rb:190:in `public_send'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/railtie.rb:190:in `method_missing'
/mnt/storage/opt/redmine/redmine/Rakefile:7:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
</pre>

**Comment by n0rvik** [comment]
Like this. This is how it works.

<pre>
[redmine@rm2-test ~/redmine]$ bundle exec rake redmine:plugins RAILS_ENV=production

== 1 AddAutowatchInvolvedIssueToUser: migrating ===============================
-- add_column(:user_preferences, :autowatch_involved_issue, :boolean, {:default=>true, :null=>false})
   -> 0.0035s
== 1 AddAutowatchInvolvedIssueToUser: migrated (0.0037s) ======================

== 2 AddHideToRoles: migrating ================================================
-- add_column(:roles, :hide, :boolean, {:default=>false, :null=>false})
   -> 0.0018s
== 2 AddHideToRoles: migrated (0.0019s) =======================================

</pre>
