### ISSUE TITLE
uninitialized constant Journald (NameError)

### ISSUE THREAD

**Issue by mboremski** [jbox-web/redmine_git_hosting#776]
From this Line:
https://github.com/jbox-web/redmine_git_hosting/blob/317602e340261da67830a38513a6b0d807c6f923/lib/redmine_git_hosting/journal_logger.rb#L3

I get this Error-Message:

```
Exiting
/home/redmine/redmine-4.1/plugins/redmine_git_hosting/lib/redmine_git_hosting/journal_logger.rb:3:in `<module:RedmineGitHosting>': uninitialized constant Journald (NameError)
        from /home/redmine/redmine-4.1/plugins/redmine_git_hosting/lib/redmine_git_hosting/journal_logger.rb:1:in `<top (required)>'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `each'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `block in eager_load!'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `each'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `eager_load!'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/engine.rb:356:in `eager_load!'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `each'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/redmine/.rvm/rubies/ruby-2.4.10/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /home/redmine/.rvm/rubies/ruby-2.4.10/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/redmine/.rvm/rubies/ruby-2.4.10/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/redmine/.rvm/rubies/ruby-2.4.10/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/redmine/.rvm/rubies/ruby-2.4.10/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /home/redmine/.rvm/rubies/ruby-2.4.10/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /home/redmine/.rvm/rubies/ruby-2.4.10/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/redmine/.rvm/rubies/ruby-2.4.10/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /home/redmine/.rvm/rubies/ruby-2.4.10/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
        from /home/redmine/redmine-4.1/config/environment.rb:16:in `<top (required)>'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from config.ru:3:in `block in <main>'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:27:in `app'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:53:in `start'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `tap'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `perform'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/command/base.rb:69:in `perform'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/command.rb:46:in `invoke'
        from /home/redmine/.rvm/gems/ruby-2.4.10/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

while starting with

`bundle exec rails server webrick -e production`

an anybody help me find out whats wrong here?
Thanks

**Comment by alexandermeindl** [comment]
Hi @mboremski 

thanks for reporting this! Most likely  your autoloading path is modified by other plugins. I fixed this with my last commit.

Let me know, if this fixed your problem.

**Comment by mboremski** [comment]
Can confirm that it works now without this error.
Thank you! :-)
