### ISSUE TITLE
custom_hook.rb:72:in `popen': Permission denied - hooks/post-receive.d/__pycache__ (Errno::EACCES)

### ISSUE THREAD

**Issue by tomhub** [jbox-web/redmine_git_hosting#785]
I'm not sure if I setup something wrong, or there is something weird.
```
remote: /var/lib/gitolite/local/hooks/common/lib/git_hosting/custom_hook.rb:72:in `popen': Permission denied - hooks/post-receive.d/__pycache__ (Errno::EACCES)
remote:         from /var/lib/gitolite/local/hooks/common/lib/git_hosting/custom_hook.rb:72:in `block in call_extra_hooks'
remote:         from /var/lib/gitolite/local/hooks/common/lib/git_hosting/custom_hook.rb:69:in `each'
remote:         from /var/lib/gitolite/local/hooks/common/lib/git_hosting/custom_hook.rb:69:in `call_extra_hooks'
remote:         from /var/lib/gitolite/local/hooks/common/lib/git_hosting/custom_hook.rb:17:in `exec'
remote:         from hooks/post-receive:15:in `<main>'
```

In addition, I had to install python onto server so I don't get unexpected error:
Calling additional post-receive hooks...
  - Executing extra hook 'hooks/post-receive.d/mail_notifications'
remote: /usr/bin/env: 'python': No such file or directory

**Comment by tomhub** [comment]
removed all hooks, reinstalled them (with current redmine_git_hosting), issue seems disappeared.

**Comment by tomhub** [comment]
Unfortunatelly, it's back.

**Comment by tomhub** [comment]
So I tested this a bit more. If I delete `local/hooks/common/post-receive.d/__pycache__' directory, then first git push proceeds without an error. However, further pushed produces warnings as above.

**Comment by alexandermeindl** [comment]
Hi @tomhub, @fairf4x 

thanks for providing a solution for this problem. I added your change to master.
