### ISSUE TITLE
ruby 3 failed to start

### ISSUE THREAD

**Issue by tomhub** [jbox-web/redmine_git_hosting#787]
Hi
Not sure if I was doing something wrong, or incorrect, here's the story. Archlinux has update ruby to v3.0, so I tried to update also redmine (outside pacman): so I git cloned https://github.com/redmine/redmine this repo (f2b17f7): was able to run redmine, but then I re-installed all plugins I had before, however, git hosting failed to run:
```
: Puma starting in single mode...
: * Puma version: 5.2.2 (ruby 3.0.1-p64) ("Fettisdagsbulle")
: *  Min threads: 0
: *  Max threads: 5
: *  Environment: production
: *          PID: 17642
: ! Unable to load application: NameError: uninitialized constant Faker::Base
: Did you mean?  Base64
: bundler: failed to load command: puma (/usr/bin/puma)
: /usr/lib/ruby/gems/3.0.0/bundler/gems/gitolite-rugged-4d24e45f97f9/lib/core_ext/faker/git.rb:4:in `<module:Faker>': uninitialized constant Faker::Base (NameError)
: Did you mean?  Base64
:         from /usr/lib/ruby/gems/3.0.0/bundler/gems/gitolite-rugged-4d24e45f97f9/lib/core_ext/faker/git.rb:3:in `<top (required)>'
:         from /usr/lib/ruby/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
:         from /usr/lib/ruby/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
:         from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
:         from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
:         from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec'
:         from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run'
:         from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
:         from /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
:         from /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
:         from /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
:         from /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
:         from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
:         from /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
:         from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
:         from /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
:         from /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
:         from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers'
:         from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!'
:         from /usr/share/webapps/redmine/config/environment.rb:16:in `<top (required)>'
:         from config.ru:3:in `require'
:         from config.ru:3:in `block in <main>'
:         from /usr/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
:         from /usr/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
:         from /usr/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
:         from /usr/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
:         from /usr/lib/ruby/gems/3.0.0/gems/puma-5.2.2/lib/puma/configuration.rb:344:in `load_rackup'
:         from /usr/lib/ruby/gems/3.0.0/gems/puma-5.2.2/lib/puma/configuration.rb:266:in `app'
:         from /usr/lib/ruby/gems/3.0.0/gems/puma-5.2.2/lib/puma/runner.rb:143:in `load_and_bind'
:         from /usr/lib/ruby/gems/3.0.0/gems/puma-5.2.2/lib/puma/single.rb:44:in `run'
:         from /usr/lib/ruby/gems/3.0.0/gems/puma-5.2.2/lib/puma/launcher.rb:181:in `run'
:         from /usr/lib/ruby/gems/3.0.0/gems/puma-5.2.2/lib/puma/cli.rb:80:in `run'
:         from /usr/lib/ruby/gems/3.0.0/gems/puma-5.2.2/bin/puma:10:in `<top (required)>'
:         from /usr/bin/puma:23:in `load'
:         from /usr/bin/puma:23:in `<top (required)>'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
:         from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
:         from /usr/bin/bundle:23:in `load'
:         from /usr/bin/bundle:23:in `<main>'

```

**Comment by alexandermeindl** [comment]
Ruby 3 is not supported by Redmine and by this plugin at the moment
