### ISSUE TITLE
GithostingShellWorker  Repository not created on disk when Sidekiq active

### ISSUE THREAD

**Issue by HighwayStar** [jbox-web/redmine_git_hosting#800]
We have upgraded redmine  to version

Environment:
  Redmine version                4.2.2.stable
  Ruby version                   2.7.3-p183 (2021-04-05) [x86_64-linux]
  Rails version                  5.2.6

and using
redmine_git_hosting 208bdb8163f3e6d2152af162a639232b6c7c9253

sidekiq gem is 6.2.2
```
021-10-18T07:46:41.821Z pid=7691 tid=3c7n class=GithostingShellWorker jid=93897a5509bf55e0cd1afb60 INFO: start
2021-10-18T07:46:41.822Z pid=7691 tid=3c7n class=GithostingShellWorker jid=93897a5509bf55e0cd1afb60 elapsed=0.001 INFO: fail
2021-10-18T07:46:41.822Z pid=7691 tid=3c7n WARN: {"context":"Job raised exception","job":{"retry":false,"queue":"redmine_git_hosting","class":"GithostingShellWorker","args":["add_repository",324,{"create_readme_file":false,"enable_git_annex":false}],"jid":"93897a5509bf55e0cd1afb60","created_at":1634543201.820981,"enqueued_at":1634543201.821029},"jobstr":"{\"retry\":false,\"queue\":\"redmine_git_hosting\",\"class\":\"GithostingShellWorker\",\"args\":[\"add_repository\",324,{\"create_readme_file\":false,\"enable_git_annex\":false}],\"jid\":\"93897a5509bf55e0cd1afb60\",\"created_at\":1634543201.820981,\"enqueued_at\":1634543201.821029}"}
2021-10-18T07:46:41.822Z pid=7691 tid=3c7n WARN: ArgumentError: wrong number of arguments (given 3, expected 2)
2021-10-18T07:46:41.822Z pid=7691 tid=3c7n WARN: /srv/redmine/plugins/redmine_git_hosting/app/workers/githosting_shell_worker.rb:17:in `perform'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:196:in `execute_job'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:163:in `block in process'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/job_retry.rb:112:in `local'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/rails.rb:14:in `block in call'
/srv/redmine/bundler/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:87:in `wrap'
/srv/redmine/bundler/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:73:in `block in wrap'
/srv/redmine/bundler/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:87:in `wrap'
/srv/redmine/bundler/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:72:in `wrap'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/rails.rb:13:in `call'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:257:in `stats'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/job_logger.rb:13:in `call'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/job_retry.rb:79:in `global'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/logger.rb:11:in `with'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/job_logger.rb:33:in `prepare'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:123:in `dispatch'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:162:in `process'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:78:in `process_one'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:68:in `run'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:43:in `watchdog'
/srv/redmine/bundler/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:52:in `block in safe_thread'
```

Repository fails to create git dir on disk

**Comment by n-rodriguez** [comment]
Did you restart Sidekiq after deploy?

**Comment by HighwayStar** [comment]
> Did you restart Sidekiq after deploy?

Sure, rechecked once more killed sidekiq, checked that there is no psidekiq process left and started it again. Same output.
